- maps/biter_battles_v2/terrain.lua
@St4telyRaven I set the multipliers to 1 so it doesn't affect current behaviour.
> mixed ore patches: adding multiplier

- commands.lua
- commands/chat_commands.lua
Need someone to test this with
> biter-battles: adding north-chat and south-chat commands

- maps/biter_battles_v2/mirror_terrain.lua
addresses this issue: https://github.com/1pulse/Factorio-Biter-Battles/issues/35
tested out locally, happy to test with others
> mirror map-not mirror reverse

- maps/biter_battles_v2/init.lua
cause many including me complain we can't defend bases on medium attacks -_- in normal-hard difficulty
> put back normal values for nades

- chatbot.lua
```on_console_chat``` doesn't use the server time + getting the server time causes it to fail, so removing it.
Also did some message changes:
- shorturl.at/demsB doesn't quite work for me, so I just directed them to the discord. 
- server-ups is not implemented in this version, so removed message [4]
- made the welcome message use yellow which seems to be more readable than the dark purple. #36
> issue-36: chatbot - on_console_chat - remove get server time as it causes problems

- commands.lua
- commands/difficulty_voting_commands.lua
- maps/biter_battles_v2/difficulty_vote.lua
- maps/biter_battles_v2/init.lua
Gives admin powers to reopen difficulty vote for 3 mins
/difficulty-revote
/difficulty-close-vote (to close voting early)
> Difficulty vote commands

- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/biter_raffle.lua
- maps/biter_battles_v2/config.lua
- maps/biter_battles_v2/difficulty_vote.lua
- maps/biter_battles_v2/feeding.lua
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/sciencelogs_tab.lua
- maps/biter_battles_v2/tables.lua
- maps/biter_battles_v2/terrain.lua
- utils/server.lua
Fixed small spelling mistakes
Replaced unused variables with "_", this is not comprehensive, mainly focusing in biter_battles_v2 directory.
Fixed a small bug where:
- Science isn't displayed on the Mutagen Log when we send 1 science pack
- Rock variable declared in terrain.lua is not used and a later declared variable is used, set to use most recently added declaration and moved up to top of file for easy editing.
I tested the scenario to the original  and no issues from the changes. I also verified the `generate_additional_rocks` function is working.
> Fixed typos & unused variables

- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/tables.lua
Added more options to send fish, updated the Tooltip with new options.
Tested locally.
Fixes #62 
Left Mouse Button			Sends one fish
Ctrl + Left Mouse Button	Sends 100 fish
Right Mouse Button			Sends half inventory
Ctrl + Right Mouse Button		Sends 50 fish
> Added options to send more fish at a time, updated tooltip

- maps/biter_battles_v2/terrain.lua
Added two turrets by silo so starting game won't be so random
> Added 2 turrets around silo

- maps/biter_battles_v2/difficulty_vote.lua
---old. if vote were 1,1,3,3  difficulty is set to 1. after fix it will set 3---
> vote fix. now will round to higher difficulty.

- maps/biter_battles_v2/functions.lua
Addresses - https://github.com/1pulse/Factorio-Biter-Battles/issues/39
> tournament mode - admin can send message as a spectator

- maps/biter_battles_v2/tables.lua
Reverts 1pulse/Factorio-Biter-Battles#91
> Revert "Update tables.lua"

- maps/biter_battles_v2/game_over.lua
Updated end game message upon Raven's request
> Updated endgame message upon Raven's request

- maps/biter_battles_v2/ai.lua
disable free silo for tournament
> torunament-feb21: removing free silo

- maps/biter_battles_v2/ai.lua
Reverts Factorio-Biter-Battles/Factorio-Biter-Battles#123
> Revert "Improve biter pathfinding"

- contributing.md
Updated Readme to include a Table of Contents
Also updated the URLs and references from the old repo to the new Repo
Added more details on how to test, solves #65
> Updated Readme to include TOC and new URL to git repo

- maps/biter_battles_v2/functions.lua
value of ammo damage modifier now can be changed for each upgrade
> changeable projectile_damage_upgrade

- maps/biter_battles_v2/functions.lua
> Laser Buff

- maps/biter_battles_v2/init.lua
buff stone and copper buy 40 and 50%
> stone copper buff

- maps/biter_battles_v2/difficulty_vote.lua
Reverts https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/17
Bringing back average instead of median
> Difficulty voting by average

- maps/biter_battles_v2/functions.lua
> flamer upgrades buff

- maps/biter_battles_v2/difficulty_vote.lua
Reverts Factorio-Biter-Battles/Factorio-Biter-Battles#138
> Revert "Difficulty voting by average"

- chatbot.lua
> update-discord-link: update chatbot.lua with correct discord link,

- maps/biter_battles_v2/feeding.lua
last lane of that function is not executing
---Fill in---
> fix revive biters

- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/tables.lua
community voted
https://discord.com/channels/823696400797138974/823771211421974579/838957717729050634
https://discord.com/channels/823696400797138974/823771211421974579/840756848591765524
> Laser and mutagen suggestions

- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/difficulty_vote.lua
https://discord.com/channels/823696400797138974/823771211421974579/839236294613794897
I accept this PR prematurely because after fun and fast, it's often hard at start. If vote end with different results we will revert / change again if needed.
> More improvements 1

- maps/biter_battles_v2/ai.lua
- Fixed bug with biters being cloned to opposite side;
- Fixed the performance degradation when silo dies with huge amount of biters around it at high level evolution %;
> Biters bugfixes

- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/terrain.lua
Reverts Factorio-Biter-Battles/Factorio-Biter-Battles#167
I cloned for we, it's work well thx so now I can revert
> Revert "few commands for WE. no need revert after event end. (i think so :D )"

- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/difficulty_vote.lua
- maps/biter_battles_v2/gui.lua
Replacement of #159 and #157 by @Max01000 with the following improvements:
* voted curve is applied to the easiest difficulty only,
* mutagen effectiveness is updated in GUI only when needed.
> 2nd attempt at increasing difficulty

- maps/biter_battles_v2/terrain.lua
When starting ores are cleared search area will expand until no more resource is found.
This has low impact on startup performance, on my machine it takes on average ~8ms even with multiple passes. The performance impact comes mainly from `LuaEntity::destroy()`, not searching itself.
> Fix truncated ores around spawn area

- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/pixie.lua
Bits' w/e game idea. 
Building will cost pixie dust 
Killing biters will give out pixie dust
Deconstructing will refund pixie dust equivalent
Pixie dust tracked per player. 
Values still need to be worked on. Table is pretty bare
Tested locally alone. Would be best to test with other ppl
- [x ] I've tested the changes locally or with people.
> Pixie dust

- comfy_panel/config.lua
- maps/biter_battles_v2/feeding.lua
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/inverted.lua
---Fill in---
- [] I've not tested the changes.
> inverse-game

- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/inverted.lua
> inverse-game: disable friendly_fire

- maps/biter_battles_v2/gui.lua
> clear-bp-history: overwrite copy history with miner

- maps/biter_battles_v2/gui.lua
> Add comment to clear_copy_history

- chatbot.lua
> discord-log-shout: log shout messages to discord

- maps/biter_battles_v2/gui.lua
> spying-fix: if you've chosen a team, remove space sci button

- antigrief.lua
Print msg to admin upon offshore pump mining
> Print msg to admin upon offshore pump mining

- maps/biter_battles_v2/gui.lua
Added join_random_button that;
- is purple
- switches player to random team when teams are even
- doesn't switch player when teams aren't even
> Add join_random_button

- antigrief.lua
Just a quick fix, does NOT mean to be permanent
> Quick and dirty way to fix desync

- maps/biter_battles_v2/gui.lua
- Deleted 2 lines printed to a player when using auto join
- Changed the dotted lines to normal ones
- Added game clock that updates with gui update
> First join gui minor tweaks

- comfy_panel/admin.lua
Added two commands:
- /kill <name> - for faster killing
- /punish <name> <reason> - for killing and banning, so that the offender drops the eq
> Ban improvements

- comfy_panel/special_games.lua
- control.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/init.lua
Added admin gui panel for creating special games!
To add config for new special game:
- Add the config to valid_special_games table
- Add button logic in on_gui_click
- Add your generate() function
Added config for two games:
- Turtle - Simple moat with given width, area it's guarding and entrance width. Does NOT check if the silo will get destroyed :)
- Infinity chest - Spawns chest(s) with given filters for both teams
Known issues:
- ~~For some reason checkbox for multiple chests doesn't work for spectators~~
> Added special_games system

- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/main.lua
Suggested by Max: https://discord.com/channels/823696400797138974/823771633021747210/919982175292624926
> Clear clipboard on game join

- maps/biter_battles_v2/init.lua
Suggestion by DrButtons: https://discord.com/channels/823696400797138974/823771633021747210/914712388194959401
> Set path_finder settings

- maps/biter_battles_v2/init.lua
Increased copper and stone size by 10%
Discord link :
https://discord.com/channels/823696400797138974/844719591828881438/908298839868461056
> Increased copper and stone size by 10%

- maps/biter_battles_v2/main.lua
Add a tag for outposters if they are over a certain distance, this update is done every minute
Discord vote : https://discord.com/channels/823696400797138974/844719591828881438/861659945543139378
> Auto tagging outpost

- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/terrain.lua
As voted https://discord.com/channels/823696400797138974/823771211421974579/922256926904025150
> Add holiday decorations to the island

- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/terrain.lua
> Revert "Add holiday decorations to the island"

- chatbot.lua
> Fixed double printing shouts for admins

- maps/biter_battles_v2/terrain.lua
Remove the landfill given back to users, as it can be used to harm server
> Fix an exploit with landfill

- maps/biter_battles_v2/init.lua
As voted, now only auto-launch is enabled
> Disabled manual rocket launch

- comfy_panel/poll.lua
As voted https://discord.com/channels/823696400797138974/823771211421974579/901789326462034061
> Disabled polls

- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/main.lua
As discussed with Ragnarok77 on discord
> perf: Small improvements to biter reanimation logic

- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
Uranium ammo research and kovarex are researched automatically only when uranium processing is researched, gate is researched when wall is researched
Discord vote links : 
https://discord.com/channels/823696400797138974/823771211421974579/982710508312477777
https://discord.com/channels/823696400797138974/823771211421974579/994194727433941062
https://discord.com/channels/823696400797138974/823771211421974579/994459774630510712
> Ura ammo and kovarex researched when ura processing is researched, same for gate with wall

- maps/biter_battles_v2/gui.lua
Show big threat values with "k" or "M" : 
Discord vote link : https://discord.com/channels/823696400797138974/823771211421974579/995801476997840976
> Show big threat value with k or m at end of text

- comfy_panel/config.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/terrain.lua
Return of last year's holiday decorations for the island. Now they can be turned on and off by the admin in the config.
- [х] I've tested the changes
> Add New Year Island decorations

- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
someone forgot to delete line that unlock it from the begining.
> fix autounlock uranium ammo after sulfur reaserch

- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/mirror_terrain.lua
- maps/biter_battles_v2/terrain.lua
The goal is to have refined concrete within walls.
I just have a little doubt about the get_replacement_time that was removed..? Is it fine or not..?
Discord vote : https://discord.com/channels/823696400797138974/823771211421974579/1041652294388830230
Example of a map generated after change :
> Refined concrete within starting area walls

- maps/biter_battles_v2/terrain.lua
Copy of #360 without merge issues
Co-authored-by: elliott-huge
> Clear area of rocks for placing silo's turret pair (redo)

- maps/biter_battles_v2/changelog_tab.lua
> [HIDDEN]Update changelog

- updateChangelog.py
As requested, renamed to DrButtons
> [HIDDEN]Script changelog updated to rename for DrButtons

- info.json
We should have an info file and keep the version updated so it's easier to track down bugs.
> Add info.json file

- maps/biter_battles_v2/changelog_tab.lua
> [HIDDEN]Update changelog again

- utils/datastore/quickbar_data.lua
- utils/server.lua
Add possibility to save quickbar (do /save-quickbar command to save it for all bb servers) or load it (do /load-quickbar command so that your quickbar is replaced by your saved quickbar). Blueprints will be ignored
https://discord.com/channels/823696400797138974/823771211421974579/1163000639907971102
> New feature : Add /save-quickbar and /load-quickbar commands

- maps/biter_battles_v2/changelog_tab.lua
Updating changelog, again and again and again, and again btw
> [HIDDEN]Update changelog again and again

- updateChangelog.py
> Updated changelog script, added new dev names

- maps/biter_battles_v2/tables.lua
Increased the mutagen values of red + green + mil + blue science.
Vote link  : https://discord.com/channels/823696400797138974/823771211421974579/1166842896465543229
> Decreased red /green and increased mil/blue science values

- maps/biter_battles_v2/changelog_tab.lua
Just minor changelog update, as usual..
> [HIDDEN]Updated changelog again

- maps/biter_battles_v2/changelog_tab.lua
> [HIDDEN]Update changelogs

- comfy_panel/player_list.lua
I was checking out Ragnarok77's PR #435 and I came across this function that seemed overly complicated.  Figured I'd update it to make more sense.  In doing so it appears to be significantly faster as well.
See the following link as a test.  Also will attach benchmark code
http://tpcg.io/_60YS57 
I tested locally, didn't see any errors.
> Refactor get_formatted_playtime

- maps/biter_battles_v2/main.lua
This fixes issues introduced in e8fd443543cf722375bfff98a7ace8f042e98ee6.
Thank you to TSP for the clear bug report!
> Fix chat messages not showing up in Discord

- maps/biter_battles_v2/feeding_calculations.lua
Specifically, this fixes an issue if player_count is set to something that does not parse as a number.  Additionally, we now accept a few more spellings of things.
> Small improvements to /calc-send

- maps/biter_battles_v2/init.lua
I've implemented the result of the discord vote in #game-vote to reduce the default difficulty setting (for games where no player votes for a difficulty) from Normal to Easy.
Change is untested.
> Updating default difficulty setting to Easy.

- benchmarking/main.lua
- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/feeding.lua
- maps/biter_battles_v2/gui.lua
This is to help special games where feeding happens without a specific player doing it.  The no-player-specified codepaths are currently unused and untested.
This is intended to fix issue #470
> Add code support for feeding without specifying player

- utils/event.lua
- utils/token.lua
These come from utils/data_stages.lua but I am not sure how often these paths are hit during play, so I decided to leave it at comments for now. Just to help understand code better later on.
A very tame change :sweat_smile:
> Comment hardcoded values for _LIFECYCLE checks

- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/feeding_calculations.lua
- tests/test-feeding.lua
This was agreed on in a community-vote poll.
I am excited by the code simplification of this change.
> Always use the new threat logic

- maps/biter_battles_v2/research_info.lua
* In the new research view, use a progress bar to represent incomplete technologies, instead of using an entire line.
* Show Factorio technology tooltips when hovering tech icons *in addition to* completion time info and percentages (the previous tooltips.)
> Research summary: use progress bar for incomplete tech

- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/research_info.lua
It now has North on the left and South on the right. It also has proper team names and colors for the team names, inner boxes around the team-specific info, and auto-updates which I think makes the UI better.
> Research UI improvements

- utils/datastore/session_data.lua
Automatically trust players after 24h of playtime (5184000 is the ticks equivalent).
Also removed useless functions.
You can see in the removed functions how it was done in comfy (it was done during the upload/download), which I didn't use when i adapted the playtime logging in this PR : https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/407)
Not sure I made a good if, it works but feel free for any improvement.
Vote : 
Link :  https://discord.com/channels/823696400797138974/823771211421974579/1230536098829308014
> Auto trust after 24h and code cleaning

- comfy_panel/special_games/captain.lua
The textbox makes it hard to kick usernames that one is not familiar with.  I also made the trustlist-manipulation fields be dropdowns as well, which seems easier.
> captains game kick from team: use a dropdown rather than a textbox

- comfy_panel/special_games/captain.lua
Many small improvements to the captains game UI from the big games today
> Captains more improvements

- commands.lua
- commands/current_map_seed.lua
* Create current_map_seed.lua
* Update commands.lua
New simple command with no arguments
> new command /current-map-seed

- functions/boss_unit.lua
- maps/biter_battles_v2/terrain.lua
See commit messages for details - fixes for multiple errors that I saw in the logs
> More errors from logs fixes

- comfy_panel/poll.lua
* poll icons actually have the right contrast!
* The poll screen takes up the width! wow!
| Old | New |
| --- | --- |
| ![poll editor old](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/49845522/70c2cafd-fceb-429e-aac4-80d9ffb0d059) | ![poll editor new](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/49845522/9072cbfd-0d57-410c-abcb-5682188fd043) |
| ![poll vote old](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/49845522/2d51c1eb-10a8-445b-b91a-7d036aa1cd67) | ![poll vote new](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/49845522/f9fe9870-732f-4354-8452-133e11f3428b) |
> Poll UI styles

- maps/biter_battles_v2/gui.lua
This also removes the "lobby" functionality, which apparently only really was used when the server was fully restarted after each game.
This also removes the text that used to appear before joining a team of "Defend your rocket silo!" and "Feed the enemy team's biters to gain advantage!".  We will have to rely on the "?" button for that context I think, or we can add the text back in if people think that it is valuable.
This also simplifies code substantially by drawing the top-left "main" GUI using the same codepath whether you have been assigned a team or not.
> Always show evo/threat

- comfy_panel/special_games/captain.lua
Thanks to califerbopbop for the report
> Fix captains pick-UI when groups are disabled

- comfy_panel/special_games/captain.lua
I'm not 100% sure if this is a good idea. But, often people are more willing to try things if it feels like less of a commitment, i.e. if they know that they can back out later on.  We can roll this back later on if it causes problems.
I also added a log statement for when the game starts, and made it easier to test the captains game code when playtime isn't hooked up.
> captains: allow players to un-volunteer to play/captain

- comfy_panel/special_games/mixed_ore_map.lua
- maps/biter_battles_v2/mixed_ore_map.lua
Add another funny ore type in special panel > mixed ore
> Special games, add ore pattern  in mixed ore

- comfy_panel/special_games/captain.lua
- maps/biter_battles_v2/difficulty_vote.lua
Difficulty is now chosen before captain start picking players instead of being it after all the players were picked, and only players playing of course can vote on difficulty. And if they stop wanna playing, their vote is removed to prevent trolls.
https://discord.com/channels/823696400797138974/823771211421974579/1259026023094288434
(just 2 days of vote but 21 yes 0 no so I feel like it will be approved...)
> Captain : Difficulty is now chosen before captain start picking players

- comfy_panel/special_games/captain.lua
> feat(captains): remove player from joiner list on disconnect

- maps/biter_battles_v2/init.lua
Based on #game-vote poll https://discord.com/channels/823696400797138974/823771211421974579/1264704415886082160
> Increase reroll time to 45 seconds

- comfy_panel/special_games/captain.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/research_info.lua
> UI updates

- maps/biter_battles_v2/functions.lua
this message will be used for patrol website.
> add message for discord server chat when match starts

- comfy_panel/special_games/captain.lua
- comfy_panel/special_games/captain_utils.lua
- locale/en/locale.cfg
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/shortcuts.lua
> Feedbacks & fixes

- comfy_panel/config.lua
let players turn of their flashlights in config
> You can turn off flashlight in config

- comfy_panel/special_games/captain.lua
- utils/utils.lua
This fix is somewhat in-depth. First off, it will no longer cause a server crash even if there is a bug in the command implementation. Second, the function now has a lot less repeated code. Last, I fixed the actual bug.
> Fix /replaceCaptainNorth command

- .github/workflows/run_tests.yml
- comfy_panel/config.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/team_stats_compare.lua
1) move 'prev' to a UI checkbox
2) always have the UI show up, just hide other-team info sometimes
3) fix 'safe' code to avoid server crashes if there is a bug
4) Add configuration of visibility to "admin config" UI
> Teamstats improvements

- maps/biter_battles_v2/gui.lua
Thanks to Max1000 for figuring out the issue.
> fix join-random

- utils/event.lua
- utils/event_core.lua
> Fix desync

- commands/where.lua
This is a bit like /where, except that it takes over your main UI.
> add /spectator-follow command

- commands/where.lua
> rename /spectator-follow to /follow for better tab-completion

- comfy_panel/special_games/captain.lua
- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/shortcuts.lua
I think that the only bug is with the "shortcut" send-science button. However, I added the check in the on_gui_click handlers just to be extra-super-sure.
> Fix bug with send-science permission

- maps/biter_battles_v2/game_over.lua
- [] I've not tested the changes.
> Add message to logging to differentiate community-picks from captain

- comfy_panel/special_games/captain.lua
As requested by Carl3 and Ncling
> Add vice-captain support

- installation-guide.md
> Added instalation guide

- antigrief.lua
As requested in https://discord.com/channels/823696400797138974/823771211421974579/1284094337088491583 i added a function that will return a message with a more detailed explanation and remaining required playtime.
I only changed bp/deconstruction check, as they require only 12h playtime. 
I did assume from context that tracker[player_name] is the total playtime from previous sessions, but i did not understand how the tracker works..
Maybe we should change the auto trust time to 12h for consistency.
> added a more specific warning for untrusted players

- maps/biter_battles_v2/config.lua
- maps/biter_battles_v2/functions.lua
- move biter area slope to config, so it can be changed easily
- remove unused configs
> move biter area slope to config

- comfy_panel/config.lua
- comfy_panel/score.lua
- comfy_panel/special_games/infinity_chest.lua
- comfy_panel/special_games/shared_science_throw.lua
- functions/biter_raffle.lua
- functions/loot_raffle.lua
- maps/biter_battles_v2/ai_strikes.lua
- maps/biter_battles_v2/biter_raffle.lua
- maps/biter_battles_v2/feed_values_tab.lua
- maps/biter_battles_v2/feeding.lua
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/team_manager.lua
- maps/biter_battles_v2/terrain.lua
- modules/show_inventory.lua
- modules/spawners_contain_biters.lua
Another batch of various fixes.
However I have encountered issue that I think is a bug. Biter commands attack_area and attack fail instantly for every biter group. It results with a well know "failed to find path to silo". I know that we experimented with pathfinder in the past and maybe have custom settings that cause an issue. Before I take it to factorio forums, maybe someone could point out where all those settings are so I can toggle to default.
> Minimal 2.0.x support | Part 3

- comfy_panel/special_games/captain.lua
- functions/boss_unit.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/gui.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/team_stats_collect.lua
- maps/biter_battles_v2/terrain.lua
- modules/show_inventory.lua
I patched remaining things that I found.
I also tested captain mode with 2 smurf accounts in multiplayer. Nothing desyncs so far.
The "remote view" lists all surfaces which I don't like, but I cannot disable it, so I'll need to make a modding request for such functionality. Every player can look into gulag and default nauvis map. It also eats a bit of screen providing no functionality.
So I cannot do more until issue with biters is solved in game engine.
> Minimal 2.0.x support | Part 5

- comfy_panel/special_games/turtle.lua
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/terrain.lua
Now it's possible to pick up landfill, so replace it with dirt-1 tile.
> Fix landfill uses

- commands/inventory_costs.lua
Don't really have time right now to investigate this issue. Disable it for now, to not break a server.
> Disable inventory-cost command

- maps/biter_battles_v2/tables.lua
- tests/test-feeding.lua
Changed them according to poll vote
> Balance mutagen values for 2.0

- maps/biter_battles_v2/ai.lua
- maps/biter_battles_v2/ai_strikes.lua
- maps/biter_battles_v2/ai_targets.lua
- maps/biter_battles_v2/init.lua
Tested several times. Rarely biters just start wandering aimlessly, but it was the same behavior in 1.1. I reverted all changes to ai files done by @RedRafe for simpler modification on my end, let me know if I should keep some changes.
> Another biter AI rework for 2.0

- comfy_panel/config.lua
- info.json
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/terrain.lua
- modules/floaty_chat.lua
- utils/core.lua
Mainly fixes comfy panel and cleans up bunch of stale code.
In 2.0 there is new option to suppress research notification, so I got rid of that as well.
> Batch of fixes

- maps/biter_battles_v2/terrain.lua
Calling destroy() on ghost in on_built_entity event causes segfault from infinite recursion if player cursor is not cleared.
> Workaround segfault when dragging pipe across river

- comfy_panel/histories.lua
- commands/where.lua
- utils/alert.lua
Mainly fixes /follow command and random utilities
> Fix uses of zoom_to_world

- functions/boss_unit.lua
- modules/floaty_chat.lua
- utils/core.lua
- utils/one_dimensional_noise.lua
Please see commit messages.
`/jail,` `/free` were partially tested, but only locally.
> Minor fixes

- maps/biter_battles_v2/functions.lua
Hopefully fixes bug with map reset when two surfaces appear at the same time due to lack of associated character
Tested only offline.
> Avoid destruction of associated player character during map reset

- commands/inventory_costs.lua
Fixed error while running `/inventory-costs` with a disconnected/dead player
Fixed all players were listed instead of the current team
Changed so players switched to spectators now included in the list too
Notice that for now 2 corner cases exists for which player character inventory is inaccessible: while player in editor mode and if disconnected player wasn't controlling a character (for example, in remote view). The first case is really rare, second case occurs occasionally if player, for example, closes the game window instead of disconnecting through escape menu. [Workaround](https://forums.factorio.com/viewtopic.php?p=653848#p653848) exists, but I decided not to implement it since it's a performance burden for too little gain.
> Fixed error while running `/inventory-costs` with a disconnected player

- comfy_panel/special_games/infinity_chest.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/init.lua
- maps/biter_battles_v2/terrain.lua
- utils/datastore/jail_data.lua
As of 2.0.26 LuaEntity::minable is deprecated and we should use LuaEntity::minable_flag instead.
https://forums.factorio.com/viewtopic.php?t=124550
> Adaptation for 2.0.26

- commands/difficulty_voting_commands.lua
I forgot to update difficulty-close-vote with new name for printing colors. Fix that now.
> Fix difficulty-close-vote command

- maps/biter_battles_v2/mirror_terrain.lua
This affected biter area_attack's pathing to the silo
> Fixed incorrect south silo tracking position

- maps/biter_battles_v2/main.lua
Profile gui refresh once per minute
I've tested the changes locally.
> Profile gui refresh once per minute

- maps/biter_battles_v2/changes.lua
- update_changelog.py
- Fix some PRs didn't appear in changelog tab
- Fix older PRs were pushed to top of a list despite being merged earlier
- Update changelog info through PR as direct push to master is protected
> [HIDDEN] changelog update

- maps/biter_battles_v2/main.lua
- utils/event_core.lua
Profile event_handlers and on_nth_tick_event_handlers every 5 seconds.
Should increase 5 seconds to 60 or so before merging. Set to 5 for reviewers convenience.
- I've tested the changes locally.
> Profile event_handlers and on_nth_tick_event_handlers

- .github/workflows/run_tests.yml
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/research_info.lua
- tests/test-functions.lua
About 25% performance increase seen if both teams have every single tech researched.
Before:
20x "update_research_info_ui" in "__level__/maps/biter_battles_v2/research_info.lua", line 483. Total Duration: 380.847845ms
After:
20x "update_research_info_ui" in "__level__/maps/biter_battles_v2/research_info.lua", line 486. Total Duration: 291.303799ms
I also added test for format_ticks_as_time that I modified.
> Minor research UI data collection optimization

- antigrief.lua
- comfy_panel/admin.lua
- comfy_panel/config.lua
- comfy_panel/special_games.lua
- comfy_panel/special_games/captain.lua
- comfy_panel/special_games/captain_community_pick.lua
- commands/current_map_seed.lua
- commands/instant_map_reset.lua
- commands/inventory_costs.lua
- commands/suspend.lua
- maps/biter_battles_v2/ai_targets.lua
- maps/biter_battles_v2/difficulty_vote.lua
- maps/biter_battles_v2/functions.lua
- maps/biter_battles_v2/game_over.lua
- maps/biter_battles_v2/main.lua
- maps/biter_battles_v2/mirror_terrain.lua
- maps/biter_battles_v2/research_info.lua
- maps/biter_battles_v2/sciencelogs_tab.lua
- maps/biter_battles_v2/shortcuts.lua
- maps/biter_battles_v2/team_manager.lua
- maps/biter_battles_v2/team_stats_compare.lua
- tests/test-feeding.lua
- tests/test-functions.lua
- utils/datastore/jail_data.lua
- utils/datastore/session_data.lua
- utils/game.lua
- utils/gui.lua
- utils/one_dimensional_noise.lua
- utils/sounds.lua
> An attempt at satisfying LuaLS

- maps/biter_battles_v2/main.lua
- utils/event_core.lua
- Fix on_nth_tick profile
- Add detailed profiling inside on_tick
> Detailed on_tick and fix on_nth_tick profiling

- modules/corpse_markers.lua
https://lua-api.factorio.com/latest/concepts/SignalID.html
> Fix corpse markers removal

- maps/biter_battles_v2/tables.lua
- tests/test-feeding.lua
buff blue +4%
nerf purple -2%
buff yellow +2%
> change balance of flasks according to poll result

- .github/workflows/stylua.yml
This will automatically create commits with a fixed StyLua.
Good for people who edit via github interface or not have StyLua inslalled
> Auto fix StyLua

- maps/biter_battles_v2/terrain.lua
increase moisture to reduce no tree maps. 
I've tested the changes locally
> increase moisture
