maps/biter_battles_v2/functions.lua
Typing in chat as a spectator:
-n <msg>  to send to north
-s <msg>  to send to south
=> biter-battles: adding option to only send msg to a specific team as a spectator

maps/biter_battles_v2/difficulty_vote.lua
Compressing the difficulty range upwards to reduce the massive round times at lower difficulties. Also adding value of each difficulty to the name field as difficulty levels 1, 2, 6 and 7 don't intuitively indicate the difficulty level outside of the voting menu.
=> Compress difficulty values upwards

maps/biter_battles_v2/init.lua
The old yield value was 0.4, but as the patch size was reduced from 2 to 1.6, this also resulted in a 20% decrease, so 0.4 was increased further to 0.5 to give the same effective overall yield
=> Updating the oil yield value from 0.27 to 0.5. 

maps/biter_battles_v2/game_over.lua
Fixing flags so it resets at the end of the game so that the MVPs get sent after every game
=> biter-battles: mvp stats only get sent once

maps/biter_battles_v2/functions.lua
Previously, the send to discord line was after the ```if global.tournament_mode then return end``` which means that no player chat is sent to discord when tournament mode is enabled. 
Moving it earlier so that player chat is still sent during tournament mode.
Compiles and tested
=> biter battle: send chat to discord even during tournament

maps/biter_battles_v2/config.lua
rocket launcher shooting distance is 36
and the explosive rocket add 6.5 more tiles
so 44 is safe
=> Make river wider against rocket launchers

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/tables.lua
Put damage modifiers to tables.lua.
- Will make it easier to make a future change to add values in gui
- Will reduce chances of logic overwriting each other
I tested it and compared damage values against 1v1 server (cause it was empty). 
You might have to rebalance grenades. 
Original value is nil, so this doesn't really do anything.
```		
global.combat_balance[force_name].grenade_damage = global.combat_balance[force_name].grenade_damage + 0.4	
```
* If there's a base modifier, spectators will not see the research upgrade values
=> Centralize ammo modifier values

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/terrain.lua
Fixes #76, use consistent maps/biter_battles_v2/biter_raffle.lua
Added warning flags when a new level of biter is spawned in the form:
`A medium spitter was spotted far away on team north...`
Warnings only occur on the first spawn of that level.
Small spitters and biters are ignored.
Let me know if the text should be different or a specific colour
Tested via sending science and viewing the notifications display at various evolution factors.
=> Notifies both teams when a new level of biter spawns

commands/difficulty_voting_commands.lua
Clear vote table on revote 
Clearing the votes will encourage actual re-voting. 1hr in, I doubt people remember their votes, so it's best to just revote. 
Upon re-voting, the difficulty level will get re-calculated similar to the logic in the beginning of the game.
=> difficulty-votes: clear vote table on revote

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/main.lua
Factorio supports events so we don't need to periodically check if a game state changed.
Joined force. In editor-mode researched `speed-module-3` and observed that `silo` and `satellite` research were completed without user's actions.
=> Refactor free silo

maps/biter_battles_v2/gui.lua
The board decided to try speeding up the initial burner phase.
They decided to provide 10 starting burner miner drill to each player.
Tested code in game, and it works.
=> Added 10 burner miner drills when player spawns

maps/biter_battles_v2/main.lua
Event was added in a way that prevented other hooks from firing.
Started scenario locally. In editor mode researched `shooting speed 1`. Observed `-80%` bonus on flamers and `+100%` on shotgun. Researched `speed module 3`. Observed that `silo` and `space science` are completed without researching.
=> Fixup silo research changes

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/config.lua, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua, maps/biter_battles_v2/terrain.lua
Removed biter health booster that causes lag due to `on_entity_damaged` firing for every damage tick to biters.
Add chance of biter revival as it used to be (`on_entity_died` happens much less often).
For future PR, balance biters after 350% evo. Currently they are indestructible as they get `0.4%` revival chance for each `1%` over `100%` evo.
Also, removed annoying spam on `stdout`.
1. I started the scenario and it didn't crash.
2. I started the scenario with biter revival changes, turned on `training mode`, in `editor mode` fed white flasks and built defenses. Observed that biters revive at `280%` evo.
=> Fix lag in long games

maps/biter_battles_v2/ai.lua
In long games it may take minutes to find a path for the next biter command. This PR should improve that. Make paths from spawners to attack vector low priority and the ones to the silo the highest.
It also changes distraction type when going for the silo. Now biters won't attack players unless they start damaging them.
Second attempt at https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/78
Closes #45 
Start a game go into training mode and debug. Observe paths and improved biter behavior.
=> Improve biter pathfinding

maps/biter_battles_v2/functions.lua
A small bug that displays the remaining seconds of spytime as decimal seconds sometimes.
=> Fixed a bug that displays the seconds as a decimal

maps/biter_battles_v2/init.lua
This is the command that guppy_face is running manually to disable mines. This will make sure guppy_face can go to sleep :P
Note: this is a temporary fix, should be replaced with proper fix to limit mines:
Suggested fixes were:
- Mines expire after a certain time
- Limit on amount of mines to be placed
- Mines are only active for a portion of time
=> Disabled mines temporarily until better fix is found

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/tables.lua
damage upgrades now can be changed independently, unused function in refined-flammables and energy-weapons-damage lists can be deleted without any consequences if value inside function is matching value inside Public.upgrade_modifiers. For example, all laser damage function rn matching data from table, so they all can be removed, while all flame damage do not match values and can't be removed (not working like that for bullets). branch of #117
=> damage updates customizable

maps/biter_battles_v2/init.lua
Reverts Factorio-Biter-Battles/Factorio-Biter-Battles#126
Mines were limited in #140 but the mine research was not enabled.
This fixes that :)
=> Revert "Disabled mines temporarily until better fix is found"

maps/biter_battles_v2/init.lua
Reverts Factorio-Biter-Battles/Factorio-Biter-Battles#144
Re-enable the disable of mines
Simple English: re-banned mine research
The mines PR #140 has an issue, it killed the server after the limit was reached and then a new round started
sanctorio re-enabled the mine research ban manually
=> Revert "Revert "Disabled mines temporarily until better fix is found""

maps/biter_battles_v2/feeding.lua
`global.reanimate` table wasn't updated, because code failed in the previous line.
Log excerpt:
```
.factorio/temp/currently-playing/utils/event_core.lua:48: Unknown ammo-category name: laser-turret
```
This fix was inspired by @maksiu1000 in PR #150.
=> Fix revive buff not applying

maps/biter_battles_v2/feeding.lua
doubling the damage bonus to biters from 100%+ evo
=> Update feeding.lua - buff endgame biters

maps/biter_battles_v2/gui.lua
Add two wood per suggestion: https://discord.com/channels/823696400797138974/823771211421974579/842809868549357579
=> Add two wood to inventory like in vanilla

maps/biter_battles_v2/difficulty_vote.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
Use the standard team name (`north` or `south`) in post-game discord message.
More stuff:
* reset difficulty when new game starts,
* display revive chance in tooltip (under `Damage:`).
=> Always use a standard team name in post-game discord message (and more QoL stuff)

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua, maps/biter_battles_v2/mirror_terrain.lua, maps/biter_battles_v2/terrain.lua
Among small bugs that this series fixes I changed core mechanics of how map chunks are generated and cloned. These commits aim to get rid of "bb_source" surface thus cutting amount of operations at runtime by half. If these changes are applied we're looking at near instant chunk generation for north side and 2x as fast mirroring for south side.
With this series of changes I prepare the scenario for further performance improvements of map generation. The goal is to move from tick driven to event driven chunk replication in order to optimize performance further.
I did what I could to test everything locally, but I did not perform any multiplayer tests.
=> Improvement to map generation performance

maps/biter_battles_v2/game_over.lua
Removes additional teleport to fix the issue from the screenshot. The issue is that you cannot move after map reset, since everybody is in the same spot.
=> Remove additional teleport during game over phase

maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/terrain.lua
default is false. it will work for every new match until u set it back to false.
"/c global.insertcar=true" enable car in starting items
"/c global.disablemixedores=true" disable mixed ores
"/c global.lootmodi=0.02" wrecks loot modifier. rise it to have more loot.
"/c global.manualmapgen=true" allow to overwrite map generation settings.
type this with your tweaks.
"/c
global.map_gen_settings.water = math.random(15, 65) * 0.01
global.map_gen_settings.starting_area = 2.5
global.map_gen_settings.terrain_segmentation = math.random(30, 40) * 0.1
global.map_gen_settings.cliff_settings = {cliff_elevation_interval = 0, cliff_elevation_0 = 0}
global.map_gen_settings.autoplace_controls = {
["coal"] = {frequency = 6.5, size = 0.34, richness = 0.24},
["stone"] = {frequency = 6, size = 0.35, richness …
=> few commands for WE. no need revert after event end. (i think so :D )

maps/biter_battles_v2/init.lua, maps/biter_battles_v2/tables.lua, maps/biter_battles_v2/terrain.lua
Continuation of: https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/175
Max requested help from me to properly rebase and apply my remarks to commits.
I took the liberty to simplify further some code areas and write additional code comments.
This change brings configurable spawn area ores system. As a consequence of this change all starting area ores are erased and ores specified within `tables.lua` script are drawn. It makes this change functional and ore density, amount of patches will differ. That's why I applied additional balancing patch.
=> Add support for configurable spawn area ore patches

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/mirror_terrain.lua, maps/biter_battles_v2/terrain.lua
Currently target pool in mid and late game is dominated by entities
of turret type. This makes biters behave dumber as they're much more
likely to target turrets next to a wall. As a consequence they throw
themselves at the most well defended part of a wall instead of going
around it and exploiting obvious pathways to a silo.
This change removes turrets of any kind from target pool. In principle
it should make biters act smarter and attack at lower angles. In my
testing on large maps with all kinds of turrets removed from the pool
pathfinder starts prioritizing holes and thin walls.
=> Remove all turrets from target pool

maps/biter_battles_v2/ai.lua
Evo reset was introduced to readjust evo/threat increase when vote is still in progress and neither team can feed. It was broken, because it ignored feeds from both teams (evo was reset to values from passive feed only).
=> Fix evo reset when admins change difficulty

chatbot.lua
When the word trust is mentioned, the server indicates to the user that they should ask a trusted player or admin to trust them.  Trusted players however no longer have the ability to trust other players.  I'm assuming this is an admin-only capability.  As such I've modified the warning text to reflect this.
Primarily, I am just learning how to contribute and learn the Biter Battle's development workflow to contribute in a more meaningful way going forward.  Am I doing it right?
=> Change text warning to accurately reflect mechanics

maps/biter_battles_v2/main.lua
Remove a vehicle from rocket silo before launching the rocket to prevent the player from riding it.  A more humane alternative than #204
=> Remove vehicle from silo

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/config.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
* Remove `global` variables to reduce memory footprint and improve performance
* Fix behavior of some parts due to wrong tick source
* Stop biters from chasing players when they should focus on destroying a silo
* Stop biters from destroying everything in the area that is 99% of a time empty
* Make surface searches smaller to decrease lag spikes
It was tested in a public game almost a year ago. Most likely needs retesting.
=> Improve biter performance

maps/biter_battles_v2/feeding.lua
Accepted in the discord vote, added infinite spy when you throw white science. I made it as simple as possible (basically, if it's white science that is being sent, just add xxxxxxxx minutes to spy timeout)
=> Added infinite spy when white science is thrown

maps/biter_battles_v2/main.lua, maps/biter_battles_v2/terrain.lua
This PR prohibits placing ghosts on the other side of the river. Sometimes ghosts can interfere with the entities on the enemy side. Especially relevant before the server is updated to version 1.1.49
=> Do not allow ghosts on enemy side

maps/biter_battles_v2/feeding.lua
As it was voted on discord, limited revive chance to 90% for biters.
Vote: https://discord.com/channels/823696400797138974/823771211421974579/876235609499398156
=> Limited threshold of biters reviving to 90% chance

antigrief.lua
There is a period of time where you can place entity ghosts, but you still cannot deconstruct ghosts
this bumps the entity-ghost placement minimum playtime  from 432,000 to 2,592,000
we do not have to put it that high, but no matter what it should be consistent between "on_built_entity", and "on_marked_for_deconstruction"
=> fix antigrief inconsistency

maps/biter_battles_v2/mirror_terrain.lua
Fix silo grief (mirroring exploit, which changes the global.rocket_silo variable, breaking bb)
I've chosen the most simple way to fix it (feel free if you have a better idea but silo is generated only on this coord (	local pos = {x = -32 + math_random(0, 64), y = -72} // 	local mirror_position = {x = pos.x * -1, y = pos.y * -1} ) 
So I'm just using that to restrict when to update this variable. I couldn't do position.y == 72 because sometimes it's 71.5 or something (which broke bb because != 72), even saw a y=82. That's why I'm doing a large range (anyways chunk this close is already made at game start so no exploit to do with this range I think).
=> Fix silo grief (mirroring)

maps/biter_battles_v2/feeding.lua
Reviving biters should be worth more threat than a regular ones. We attempted reducing subtracted threat when they revive, but it didn't work (most likely a rounding error). This PR tries to increase threat income by multiplying it by expected number of biter lives. It should mitigate the issue that in the worse case caused negative threat without threat farming.
This PR can also slightly improve performance of `set_evo_and_threat` function by moving references to global variables out of loop that iterated over each flask separately.
=> Add more threat to compensate revive

maps/biter_battles_v2/main.lua, maps/biter_battles_v2/mirror_terrain.lua
Adds decoratives for the south. In approximately the same places and quantities as in the north
=> Mirror decoratives to south

maps/biter_battles_v2/main.lua
Renamed autotag name to just East or West isntead of East/WestOutpost
Vote link : https://discord.com/channels/823696400797138974/823771211421974579/924224832122540062
=> Renamed autotag to just East or West for shorter name instead

maps/biter_battles_v2/gui.lua
Cancel crafting queue when going to spectate
Code talk : 
I went from end to start because otherwise when I deleted the element 1 of the crafting queue, the index changed and the looped crashed because -1 element. Also added a double check for player.crafting_queue because one time, code broke(I didn't go to spectator island) because no condition with just player.crafting_queue[i] so I added another check on player.crafting_queue.
Discord link : https://discord.com/channels/823696400797138974/844719591828881438/889255782917492746
=> Cancel crafting queue when going to spectate

chatbot.lua
Current link does not exist as user has either deleted or privated the repo. This changes the chatbot to provide the correct link.
=> Change GitHub link to this GitHub

comfy_panel/special_games.lua
New special game. Prevent choosen entities from being placed by players.
Can be set for both teams together or separately for each.
=> Special game: Disabled entities

maps/biter_battles_v2/game_over.lua
As voted, every message after silo's destruction is visible for everyone
=> Added auto-shouting after game ending

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/main.lua
Rocket silo is no longer automatically unlocked after speed module 3
Space sci is automatically unlocked after rocket silo
Moved the function to main.lua so that ai.lua is just about controling biters
=> Removed auto research of silo

comfy_panel/special_games.lua
Changed order of config option so that all choose-elements are aligned to the left
Changed "operable" option in infinity chest to default false
=> Special games gui tweaks

maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/gui.lua
Added new button that allows for feeding all the sci in inventory at once. Prints just one line. Discord messages unchanged for compability. Allows for ascending and descending order of sent sci
Visual look is open for discussion
=> Added mixed send functionality

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/terrain.lua
Basically to improve performance : saw in a profiler than find entities is quite heavy when defense are being replaced automatically by bots, The idea was not to do this kind of find entities on 70 radius when it's far from nests.
Function was copied (with noise removed) because I couldn't import terrain from functions (too many c level..).
I did +140 distance to be sure that it's not nearby nests (to avoid any kind of exploit with this change, and anyways even if it's a bit a big number, since barely no ones build defense and have active defenses there, it should be fine, if you want we can reduce the 140 number, just arbitrary but ugh, felt correct enough when testing locally.
=> Perf : No find entities used when defense are built are far from nest

maps/biter_battles_v2/init.lua
Spectators are able to rotate ghosts. This PR prevent it.
Cons: there will be no more players spinning on the island.
=> Fix ghost rotation by spectator

maps/biter_battles_v2/gui.lua
When you switch to spectator mode while in a car or other vehicle, the character does not teleport to the island but stay as spectator in the vehicle. This PR changes so that the player is teleported to the island even if they are in a vehicle.
Fixes #293
=> Fix spectator in vehicle

maps/biter_battles_v2/init.lua
Allows for use of `/editor` and `/config` commands while on the island
=> Enabled editor and config in spectator

comfy_panel/special_games.lua, maps/biter_battles_v2/terrain.lua, utils/event_core.lua
Fixed errors from special_games
Added the path to the actual function causing the error to logged line in event_core.
Resulting in more helpful info:
Fixed errors caused by special_games
=> Added path to errors from event_core

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/config.lua, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/init.lua
Check here for details : https://discord.com/channels/823696400797138974/984991352909611040
But the summary is that with bosses, you spawn one more wave when a normal biter wave is being, issue is that threat is local for boss wave spawning and normal biters wave boss, to fix that issue, divide by 2 threat (normal biters get half of threat, boss get half of threat), so now, you don't spawn too many biters anymore, which stops the negative threat issue happening too often.
Second thing is that the loop for threat : Another issue is that the check for threat is done at the beginning of loop when spawning biters, not end.
Imagine you have a 5K wave threat to spawn. You spawn bosses, you are at 4950 threat wave, a new boss could cost for example 1k threat to spawn. Still in the loop, threat …
=> Fix threat boss issue going negative too often (waves were oversized) and frozen boss bug and added boss announce

comfy_panel/main.lua, utils/profiler.lua
Enabled profiler module so that we can start it during endgame to get a reference point for further updates.
Added dumping to file
Downsides:
Seems to amplify lag spikes (eg for map gen)
=> Enable profiler

comfy_panel/main.lua, comfy_panel/poll.lua, maps/biter_battles_v2/difficulty_vote.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/team_manager.lua, modules/simple_tags.lua, utils/gui_styles.lua, utils/utils.lua
Replaced not-so-useful `element_style()` from `utils.gui_styles` with `gui_style()` in `utils.utils`.
The goal is to cut down number of lines needed to format a gui element.
Possible downsides: tiny performance impact related to the `for` loop.
This PR was created to break #324 into smaller, more managable chunks
=> Replaced element_style() with gui_style()

comfy_panel/special_games.lua, maps/biter_battles_v2/gui.lua
This fix remove `has_life` function from `global`. According to the lua api  
https://lua-api.factorio.com/latest/Global.html
**_Functions are not allowed in `global`_**
To reproduce the bug:
1. Need a multiplayer at least 2 players.
2. Activate special game Limited lives
3. Spectate
4. Try to join team again. 
5. Desync.
=> Fix Limited lives desync

maps/biter_battles_v2/init.lua, maps/biter_battles_v2/terrain.lua
The main change in this PR is that the water around the island is now considered part of the river and is generated with it.
Previously, the water around the island (spawn circle) was drawn on top of everything, now only the island is drawn this way.
Features
- Only one function to check the river, no need to do extra check on spawn circle
- The water around the island is now exactly 39 tiles as specified
- No fish under island
- Added a single check for the river when generating the starting area, which should fix #174 for sure
=> Change river function

maps/biter_battles_v2/difficulty_vote.lua
Some players tend to vote same difficulty many time in short period of time. Each vote print same messages in chat. This code prevent printing in chat message if the current vote is same as previous.
=> difficulty_vote: prevent voting same difficulty.

maps/biter_battles_v2/ai.lua
message printed in chat when biters are spotted kept default names "north" "south" after those names got changed in team manager.
=> fix team name on biters spotted

maps/biter_battles_v2/gui.lua
show game speed next to game time
=> feat(gui): show game speed next to game time

comfy_panel/group.lua
Don't let players make a group if the group name is already taken.
Fix for https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/350
=> Do not allow players to create a new group with the name of an existing group

maps/biter_battles_v2/main.lua
Sometimes you see the following error in log : bad argument #3 of #3 to __index (string expected, got nil) in the if, this PR should fix it (I couldn't reproduce it...) but from the line of if, only player_index which can be optional seem to be a cause of this issue.
Should fix https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/308
Maybe someone has more info..
=> Bugfix to avoid spam of error in log when decon

comfy_panel/special_games.lua, maps/biter_battles_v2/feeding.lua
Special event I heard requested multiple times, basically evo is identical between both teams and the throw is shared for both teams (same +threat and +evo).
=> Special event shared evo and throws

comfy_panel/special_games.lua
Add item in admin GUI special games tab to send players to external server
so that we don't need to find the command everytime
=> feat: add send to server in admin gui

maps/biter_battles_v2/team_manager.lua
Fixes https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/370
Set permission selected_tab_changed to true even when frozen so ui not broken anymore for special/groups
How to reproduce bug :
Freeze players, join a team, try to acecss for example special games or group...
Workaround meanwhile : 
`/c     local p = game.permissions.get_group("Default")         p.set_allows_action(defines.input_action["gui_selected_tab_changed"], true)`
=> Set permission selected_tab_changed to true even when frozen so ui not broken anymore for special/groups

comfy_panel/group.lua
[Comfy already did this ](https://github.com/ComfyFactory/ComfyFactorio/blob/3cd408b65e6f97ab812fc8b81ff8c7f9c6299a98/utils/gui/group.lua#L238)
People may be more wild with naming but I don't see obvious flaws in it.
=> Allows group name and description to include spaces and punctuation characters

maps/biter_battles_v2/init.lua
This permission is required to be able to change tabs in Select icon gui.
Currently, spectators do not have this permission, so only the first Logistic tab is available to them.
=> Allow change_active_item_group_for_filters for spectators

modules/show_inventory.lua
Fixes #319
Change how /inventory works to make it more efficient.
- no more iterating over `connected_players`
- only get category matching active tab in GUI
- only update relevant inventory GUIs, not all of them
- you can `/inventory` yourself. changed for testing, though I'm not sure why this wasn't allowed before
=> Improved /inventory performance

comfy_panel/config.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua, utils/token.lua
Reveal map at start for 2k distance, first both team, then 3 minutes later, do a second reveal so south has the map too as the mirror was not yet done, so to see ores in south you need this second scan.
Toggleable by admin
Vote :
https://discord.com/channels/823696400797138974/823771211421974579/1127593258940366859
+ second one : 
https://discord.com/channels/823696400797138974/823771211421974579/1113151225098162358
=> Reveal map at start

maps/biter_battles_v2/gui.lua
Ragnarok77 ran some profiling and found that ~9% of the time spent in lategame threat farming was spent on updating the gui threat values. This attempts to solve that by precomputing the threat text, and applying it to every gui, rather than computing the threat text for every gui individually, and lengthening the time between threat updates (from every 5 ticks, to now every 30 ticks)
This PR is an alternative to https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/393 where we removed subsecond threat updates entirely.  I have a suspicion the creation of the threat text was the majority of the runtime but I cannot be sure.
```
===
Last thing, here is a the summary of late game threat farmer lag : 
194694x "anonymous" in …
```
=> perf : Increase refresh threat min delay and optim on code

functions/boss_unit.lua
As in title, we filter out damage events for a type of LuaEntity "unit". The "unit" here is any biter. This change should improve performance during a threat farming and defending as we won't have to process events dedicated for nests, tress, turrets, worms and other structures.
Additionally I limited the amount of HP bar updates to 2/s, instead of 6.25/s.
=> perf : optim damage event  and increased refresh delay for healthbar of bosses

utils/event_core.lua
Fix #390 
The possible way of how to iterate and call all valid `handlers` if some of them may be `table.removed` in process 
+ Pros: No more crash on `nil` handler
- Cons: deepcopy of all event handlers on `on_event`
=> Fix server crash on `debug_getinfo` with `nil` handler

comfy_panel/player_list.lua, maps/biter_battles_v2/init.lua, utils/datastore/session_data.lua, utils/server.lua
Playtime has been broken for a very long time, it requires to be stored on the server, here is the PR that makes it possible, by showing messages in server log.
I also cleaned a bit some unused code.
It will upload playtime to server every 15 minutes, or when a player leaves.
It will set the total playtime when a player joins.
=> Bugfix : total playtime is now logged

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/ai_strikes.lua
* Currently, two independent strike vectors are being calculated for waves that spawn an additional boss unit group together with the non-boss unit group
* This change makes it such that the boss and non-boss unit groups will use the same strike vector, resulting in them traveling together as one pack
* Gameplay-wise, this will result in boss-enhanced waves packing a more focused punch.
=> fix boss units not traveling with the pack

maps/biter_battles_v2/main.lua
This should help spectators see what is going on. It ends up being slightly redundant with the message already printed by the game engine, but with the additional context of which team it is for.
Possible log output is now:
foo started research Automation
Completed research Automation
Team north completed research automation
- I've tested the changes locally (this version had slightly different text, but I've run it since then) <img width="328" alt="Screenshot 2023-11-02 at 1 49 21 PM" src="https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/273840/c9a9ec71-1c0b-4ad6-8c4c-841fe77bbf81">
https://discord.com/channels/823696400797138974/823771211421974579/1170622174621597747
15/11/2023 :
=> Add a spectator-force log message about which team completed a research

commands/chat_commands.lua
This is useful if users that are admins want to spectate games and chat with just the spectators.
This came up when mysticamber was accidentally broadcasting because they are an admin.
For reasons that I do not totally understand, when an admin user is a spectator, all of their chats are automatically broadcast (almost as if using /s) to all forces. This only happens when they are on the spectator force (due to [these lines](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/blob/97c32c241cdb5232cf346f78c20434c57e2bd2d7/maps/biter_battles_v2/functions.lua#L354-L355)). This command allows admins to work-around this behavior.
An alternative would be to remove the lines above, which would remove the "admin users always broadcast their chats". Yet another possible option would …
=> Add /spectator-chat command

maps/biter_battles_v2/feeding.lua
This took me a while to figure out when reading the code, so I thought that this comment might help others.
=> Add comment documenting advantage of sending science in large batches

commands/misc.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/init.lua
Allow restart map during ongoing map reroll countdown (`/instant-map-reset`)
Allow cancel ongoing map reroll countdown by toggling config 
Fix map reroll default config. Map reroll is enabled by default after first map restart on the server
=> instant map reset can be done during map reroll + default yes map reroll + added possibility cancel map reroll

maps/biter_battles_v2/game_over.lua
Resets game speed to 1 after the game has completed. This allows the reset game timer to complete at normal speed.
=> Reset game speed to 1 after silo death

comfy_panel/player_list.lua
fix #294 
alternative to #355
This pr add prefix for all username elements in the list so they have distinct name not just a number.
The poll button is not the only one that can cause bug #294
More rare case but, the arrows in the team manager can also cause the bug:
This pr also fixes it, while #355 doesn't.
=> fix poll button opens random player camera

maps/biter_battles_v2/terrain.lua
This PR does 2 things:
1. Slightly increases the sizes of the Mixed ore patches.
2. Reduces (can't fix fully) the issue where sometimes Mixed ore patches were severely cropped off near Main. Now with these changes it happens only rarely.
=> Increase the size and edit ratio of mixed patches 

comfy_panel/player_list.lua
Ranks are now correctly shown with playtime after this bug fix in "fish" => players tab.
Fixes https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/431
=> Fix playtime rank

maps/biter_battles_v2/team_manager.lua
Allows players to create, remove and modify tags when they're frozen.
=> Allow tag manipulation when frozen

comfy_panel/group.lua
fix group names that overlap with luaguielement
We had someone set group names to "help" which caused the following error:
```
17910.825 Script @/utils/event_core.lua:57: [ERROR] Invalid name "help": LuaGuiElement contains a property or method with the same name. in ...ort/factorio/temp/currently-playing/comfy_panel/main.lua:133
```
To get around this, we prefix the group name by `__` before setting it in the gui, and then remove the `__` when accessing our internal representation.
=> fix group names that overlap with luaguielement

.github/workflows/run_tests.yml, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/feeding_calculations.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/main.lua, tests/test-feeding.lua
This series of commits reworks how evo/threat increases are calculated to no longer iterate through the flasks one at a time. Additionally, it adds a command that allows users to see the expected evo/threat increase from a given send (defaulting to the contents of their inventories, but fully customizable).
Additionally, this adds the first (?) unit test support to the repository, allowing some functionality to be tested in a pure-lua environment (no factorio running).
I highly recommend reviewing this commit-by-commit, as most of the commits are no-ops in terms of behavioral changes.
I am very open to feedback about how the change should work, and the UI of the /calc-send command itself.
=> revamp evo/threat calculation, and add /calc-send command

functions/boss_unit.lua
Before this change, boss unit deaths aren't properly tracked. This change fixes that issue.
I tested this locally, no issues.
=> fix boss_unit death tracking

maps/biter_battles_v2/gui.lua
Automatically clear_cusor when spectating, otherwise it is a bit confusing to have something in your cursor/hand when on spectator island.
I tested this by putting things in my hand, and then clicking the "spectate" button, and seeing if things stayed in my hand.
=> Automatically clear_cusor when spectating

maps/biter_battles_v2/terrain.lua
I get this error when I run the biter battles scenario with map settings of width=50, height=50.  Not that this is a reasonable way to run the scenario, but somehow this is how the settings are if I use --load-scenario when starting factorio.  Also, even if this is not a good choice/setting for running the game, it seems best if we don't have any crashes/lua-errors when running in that configuration.
=> Avoid "LuaTile API call when LuaTile was invalid." error

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
This will change the "Time:" displayed in the GUI to show 0:00 when the first player actually mines or crafts an item. I think that this is especially valuable in captains games, which often include 20+ minutes of team selection and discussion before the game actually starts. I could potentially also hook into on_player_changed_position to cover even more cases, but this seems good enough for a first pass.
There are other ways that could potentially accomplish the goal behind this change.  For instance, we could pause the timer whenever global.freeze_players is set to true. This would work well for captains games, but wouldn't help in public games where nobody joins for 10+ minutes.
There is some slightly related logic in the passive feeding code (in ai.lua:raise_evo) that doesn't do any …
=> Game start time: set it to 0 when something actually happens

maps/biter_battles_v2/feeding.lua
Only if space-science is sent, obviously.  It felt like a bug that using the send-all button wouldn't grant this.
=> Grant infinite-fish-vision when using send-all

maps/biter_battles_v2/feed_values_tab.lua, maps/biter_battles_v2/main.lua, maps/biter_battles_v2/sciencelogs_tab.lua
Add a new tab displaying mutagen values and resource costs
I feel like this gives a lot of context for why sending higher-tier
sciences is worth more, and having this information available will
make new players learn the game faster. Note that I made some pretty
arbitrary decisions in the "cost" column. Specifically, which recipes
to assume the use of productivity modules for, and the relative cost
of each ore type and crude oil, as well as just blindly assuming that
all of the different petro/light/heavy oil are the same cost as
crude. That said, I think that this still gives a pretty accurate
picture of the costs/values of the different sciences.
Also, people have talked about potentially making a mode that slightly
randomizes the effectiveness of different sciences (or potentially
even …
=> Add a new tab displaying mutagen values and resource costs

comfy_panel/group.lua, comfy_panel/special_games/captain.lua
Group-names were previously colliding with the luaguielement parameters and functions.  To overcome this, we started prepending '__' to each group name, see commit 0b53b2b
The captains code wasn't updated at that time, so this commit aims to update the captains picking code to search for '__cpt' instead of 'cpt' when selecting members of a group.
This seems like a reasonable change to me, but would need multiple people to test.
=> Sync safe group-name with captain group picking

antigrief.lua, comfy_panel/score.lua, control.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/main.lua, maps/biter_battles_v2/terrain.lua
This is a partial PR from https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/410
The purpose of this is to simplify the codebase, and in doing so, make the gui-rewrite easier. By pushing this to a separate PR, it should be easier to review and evaluate.
The way Event.add is used now leads to confusion w/r/t the order of operations, as well as makes debugging (and thus development) slower.  By incrementally moving single events to this method of dispatch, we will enable ourselves to delete more code, and expedite the gui-rework.
I tested this code locally.
=> move on_player_mined_entity to control-dispatch

utils/event.lua
fix `Event.add_removable_nth_tick_function` after debug module was removed in #439
=> Fix Event.add_removable_nth_tick_function

comfy_panel/score.lua
All killscore values are changed to be 4x the biter's threat value. This is slightly higher than the previous killscore value for biters, and much lower than the previous value for worms and spawners. I've also removed the killscore values for enemies that are impossible to kill in BB (hostile turrets, players).
=> Update killscore to be proportionate to threat

maps/biter_battles_v2/main.lua
This might currently be breaking things like turret creep, landfill trust, and enemy ghosts.  Yikes.
=> Fix on_built_entity

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/config.lua, maps/biter_battles_v2/feeding_calculations.lua, tests/test-feeding.lua
A new option is added (which defaults to off, but we will probably
test for a few weeks). When the option is turned on, the following
things happen:
1. There should be zero change to anything below 100% evo, and almost
no change below ~150% evo.
2. There is no longer a big batch-send bonus that results in bonus
threat for doing a send that results in 325% evo.
3. Late game threat values will look lower, but will go down much more
slowly.
4. Sends when around 200% - 300% evo are probably more powerful than
they used to be.
5. Threat should no longer sometimes go negative after defeating large
attack waves at high evo% values.
There are two unexpected-behaviors (bugs?) in the code today, both
related to high revive% cases (i.e. they happen as evo% approaches
325%).
1. Large batch-send …
=> Add experimental new threat logic

commands/suspend.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua
Suspend was implemented but allowed people outside of the suspendee's team to grief the vote by just randomly voting.  This limits the voter pool to those on the suspendee's team.
To enable this, I had to add information about the suspender to the global table, and to do this I wrapped most of the important suspend-related information into a class 'SuspendTargetInfo'.  There are parts of the global suspend table that could likely be included, but I would like to keep this simple if possible.
=> Limit suspend voting to suspendee's force

comfy_panel/main.lua, utils/profiler.lua
See #483 
Not closing that as fixed, because imo a fix would be a working replacement to current profiler.
There's [Instrument Mode](https://lua-api.factorio.com/latest/auxiliary/instrument.html) but it's not for multiplayer and looks like for fully fledged mods only.
=> profiler.lua: gracefully disable profiler in unsupported versions

utils/event_core.lua
This has annoyed me so much. I am unreasonably excited about this change.
Specifically, before this change, we might see an error like the following:
```
16.678 Script @/Users/cliff/factorio-local/Contents/temp/currently-playing/utils/event_core.lua:46: [ERROR] LuaEntity doesn't contain key x. in ...ts/temp/currently-playing/maps/biter_battles_v2/main.lua:243
```
And after this change, we instead see an error like this:
```
11.962 Script @/Users/cliff/factorio-local/Contents/temp/currently-playing/utils/event_core.lua:30: Error caught: LuaEntity doesn't contain key x.
11.962 Script @/Users/cliff/factorio-local/Contents/temp/currently-playing/utils/event_core.lua:32: stack traceback:
...cal/Contents/temp/currently-playing/utils/event_core.lua:32: in function …
```
=> Fix error printing to show real stacktraces

comfy_panel/special_games/captain.lua, utils/color_presets.lua
Captain game text: better position for spawn text
Turn the captain_versus_float color brighter yellow
captain.lua: Change Versus mode text color to be readable
It has been magenta on aqua (water tiles) until now. It was not a
pleasant color combination to read even with good color sight. Changed
the vesus color to orange, it's supposed to be better for color
blindness palettes I've found.
color_presets.lua is mixed type between 0-255 and 0-1.0 for now...
captain.lua: Refactor generateText -> renderText
- changed name
- reduced number of arguments to avoid mistakes
- position arg is now a table (passed through)
- color arg is now a table (passed through)
- fixed another copy-paste instance of versus-game not having alpha
argument
Restructure and fix Captain game text line
Fix: text size …
=> Change color, fix and refactor Captain mode text

benchmarking/main.lua, control.lua, maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/ai_targets.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
Specifically, by doing a bit more work when we start/stop tracking units, we can get constant-time-indexing support for fast random building selection.
This was reported in issue #476 as something that can slow down large captains games.
=> Speed up ai_targets random target selection

comfy_panel/poll.lua, utils/game.lua, utils/server.lua
Removes the function `Game.get_player_by_index` which had several uses in two files, replacing with a functionally identical `LuaGameScript::get_player` from the official Factorio Lua API. Also removes the function `Game.get_player_from_any` which had zero uses and also replicated the functionality of the official API. This reduces code complexity and eliminates the need for Factorio to copy the entire player table to Lua.
=> Remove Game.get_player_by_index and Game.get_player_from_any

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua, maps/biter_battles_v2/research_info.lua
This is meant to replace the white-flask that allows spectators to view research progress during captains games. Specifically, the current implementation bothers me because it actually moves players between forces, which I believe introduces many possible races/confusion/bugs. I also hope that this implementation might be more useful, as it shows a comparison of both teams at the same time.
I believe that bugs with the existing implementation led to the decision to only enable the white-flask during captain's games. I hope that this new implementation can be enabled in all games.
For now, it is disabled by default, but can be enabled by setting
`global.bb_show_research_info = "always"`
or
`global.bb_show_research_info = "spec"`
to enable it, and setting
`global.bb_show_research_info = …
=> Add a new research info window (disabled by default)

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/init.lua
It has always slightly bothered me that the rules for what count as overlapping flamethrower turrets are not super clear/explicit, and are very annoying to enforce on new players that don't know the rules.
If there is already one flamethrower turret placed, this prevents another flamethrower turret being placed that is facing the same direction within a 48x2 box centered on the already placed turret. Thus rows of flamethrower turrets must be at least 24 tiles apart (front-to-front).  This distance was chosen because flamethrower turrets have a min range of 6 and a max range of 30.
I added a global variable that can be used to disable this behavior (mostly just in case it causes a strange performance issue or otherwise unexpected bug).
To disable this functionality, run
/c …
=> Implement flamethrower turret overlap protection in code

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/init.lua
Changes to the pathfinder to
- Make the short path cache much bigger and increase the minimal length of a path to be cached into the short path cache to make sure that really short paths and thus fast to compute won't fill the cache and override longer paths. I found the value of 12 by testing some and taking the value that filled the cache to a little less than 100% when waves attack walls. Should reduce lag.
- Increase the minimal length of a path to be cached into the long path cache to reserve this cache for wave paths. With this setting set to 60, I have seen some situation where a group of biters will be distracted by something (and each of them will calculate a 1 path to that thing) that is more than 60 tiles away and thus completely override all the 50 wave paths cached. This …
=> Changes to the pathfinder settings

comfy_panel/group.lua
As much as it is cute to name a group "(wisper)" or to do smart things with rich text, it seems more usable and less surprising if we just don't allow it.
=> group names: do not allow "()[]" characters

comfy_panel/admin.lua
This can be used to teleport a player to spawn position.  This is functionally fairly similar to "Kill", except that they can keep their inventory and it is possibly less offensive.
Additionally this makes the various teleport options work even if players are driving (it just removes them from their vehicle first, the vehicle will be left behind).
=> Admin option: MoveToSpawn

comfy_panel/player_list.lua, comfy_panel/special_games/captain.lua
Add total play time information in picking popup of captain, list is now ordered by playtime, while keeping having groups together.
Result : 
To test it easily : 
/c global.total_time_online_players["qqqq"] = 66666
I tested it locally with 4/5 local factorio, it seemed fine. 
Vote : 
https://discord.com/channels/823696400797138974/823771211421974579/1236564023336501268
=> Captain : Add total playtime in picking up and ordered by playtime

control.lua
Bug: mining history is empty 
Problem: `Antigrief.enabled` is a local variable and cannot be accessed from `control.lua`
Solution: Don't check `Antigrief.enabled` in `control.lua`, it is checked immediately in `Antigrief.on_player_mined_entity` anyway
=> Fix mining history is empty

comfy_panel/special_games/captain.lua
Remove all the markers (red line and circle) on the island that splits the island visually in 4 (speedrunner, vet, not new not vet, new player) and remove the spectator island part in green, which were shown during picking phase
Vote : 
https://discord.com/channels/823696400797138974/823771211421974579/1237122117619945493
=> Captain : remove ground markers of new/not new/vet/speedrunner and spect part

comfy_panel/special_games/captain.lua, maps/biter_battles_v2/main.lua
This was voted on by the admins and universally agreed to be confusing behavior. It is confusing for admins because they have to remember to use /spectator-chat. It is confusing for non-admins because they see chat messages that are not /shouts from other players, and assume that perhaps their chat messages work the same way.
=> Stop always broadcasting admin chat messages

commands/instant_map_reset.lua
Useful if in captains games someone joins the map and places something before the event starts.
=> support "/instant_map_reset current" to reset to current seed

maps/biter_battles_v2/sciencelogs_tab.lua
Specifically, if one game has sends, then global.science_logs_date will be non-nil.  The global initialization logic only sets science_logs_text to nil at the beginning of each game.  Thus, only global.science_logs_text should be checked for nil-ness to figure out if there is any science logs to show.
I found this when randomly looking at server logs, and I saw the following error:
```
3685.453 Script @/opt/factorio1.1.42/temp/currently-playing/utils/event_core.lua:30: Error caught: ...rently-playing/maps/biter_battles_v2/sciencelogs_tab.lua:162: attempt to index field 'science_logs_text' (a nil value)
3685.453 Script @/opt/factorio1.1.42/temp/currently-playing/utils/event_core.lua:32: stack traceback:
...ctorio1.1.42/temp/currently-playing/utils/event_core.lua:32: in function '__index' …
```
=> sciencelogs: fix a bug when looking at the UI before any sends

comfy_panel/special_games/captain.lua
Expansion of #514. Uses Factorio UI styles (`green_button`, `red_button`, `submit_button`) instead of setting the font color on buttons.
This enhances the readability of the buttons.
=> Use Factorio button styles instead of font color on Captain UI elements for enhanced readability

comfy_panel/admin.lua, comfy_panel/config.lua, commands/chat_commands.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
Right now, if any chat message you can see contains "@username" or "@ username", or if someone whispers at you, then the following effects happen:
1) if you are at 100% health, you take 1 damage
2)A popup appears near the top-center of the screen with the message contents, which disappears after 10 seconds (the one popup will contain multiple messages in it if you get many pings at a time)
3) A 'new_objective' sound plays at 0.6 volume
I considered also drawing an explosion at the location of the player or something, but it seems unnecessary to me compared to the popup.
Right now, this needs to be manually enabled under Fish -> Config for each user that wants to see the ping effects.
I'm hoping to eventually enable something like this by default (although people could still disable it), …
=> Initial/experimental support for @ping in chat

comfy_panel/special_games/captain.lua
1. Add tooltips to some buttons so that they do not claim that pressing 'e' will work
2. Only print out 'Initial Picking Phase done - group picking is now disabled' once
3. Rename 'Cpt Player' to 'Join Info' to try and make new-player-joining experience clearer
=> tiny captains game cleanups

utils/queue.lua
This is currently unused in practice, so it has never mattered.  I wanted to use this in a special-event code that I was working on, and discovered the brokenness.
=> utils/queue: fix off by one error

maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/init.lua
This gives an option of easily running a special where evo and threat grow at different than normal rates.  i.e. 25% mutagen effectiveness but 4x as much threat as normal, or 500% mutagen effectiveness but 0.1x as much threat as normal.
=> Add global.threat_multiplier

maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/feeding_calculations.lua
Error:
```
15268.741 Script temp/currently-playing/utils/event_core.lua:30: Error caught: ...temp/currently-playing/maps/biter_battles_v2/feeding.lua:225: attempt to index local 'i' (a nil value)
15268.741 Script /temp/currently-playing/utils/event_core.lua:32: stack traceback:
.../temp/currently-playing/utils/event_core.lua:32: in function '__index'
...temp/currently-playing/maps/biter_battles_v2/feeding.lua:225: in function 'feed_biters_from_inventory'
../temp/currently-playing/maps/biter_battles_v2/gui.lua:571: in function <..../temp/currently-playing/maps/biter_battles_v2/gui.lua:516>
[C]: in function 'xpcall'
.../temp/currently-playing/utils/event_core.lua:49: in function 'call_handlers'
.../temp/currently-playing/utils/event_core.lua:61: in function …
```
=> Fix error on non exist inventory

comfy_panel/config.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
This has a variety of changes
1. \@Ping support defaults to "on", but it can be turned off at Fish -> Config
2. The Ping popup looks better at a variety of display scales
3. /ignore now works properly to block the ping popups
4. you can use any of "username\@" "\@username" or "\@ username" to message someone.  The first and last ones of those are easiest to use with factorio's tab-autocompletion
5. Even if you move the window to the bottom-right of the screen, and then resize your window to be smaller, the next popup will still be visible
=> Ping improvements, and default to on

comfy_panel/special_games/captain.lua, comfy_panel/special_games/captain_random_pick.lua, maps/biter_battles_v2/team_manager.lua
This takes, as an input, a coarse-grained view of how good players
are, and then makes two random teams that are mostly-fair. At the
moment, it relies on the referee to build this
approximate-stack-rank. However, I plan on possibly allowing
captains to also take part in it as well.
This also allows referees to configure more things after the special
has started (but before captains are finalized).
I spent way too long figuring out that "freeze_players" made it so
that people could not interact with switches in the UI.
I also added a test-only command that is very very useful for me when
testing this functionality.
=> Captains games: add randomized-fair picking mode

maps/biter_battles_v2/init.lua
This is primarily motivated because I believe that the high value of short_cache_size was drastically hurting performance in some situations, based on
https://forums.factorio.com/viewtopic.php?p=610324#p610324
So, the main thing that I wanted to do here is to move things closer to their default values, and closer to the values that they were before #502.  Note that I am leaving the lower-pathfinder-resolution, as I assume that that is still a big speedup for the pathfinder in general (even though the downsides are substantial).
I also added documentation of default values.
I wish that I could tell you that this change is based on actual concrete testing, but it is not. It is based on my own gut feeling that overall, after #502, some things got worse and other things got better, and that …
=> Partially revert pathfinder settings change (#502)

comfy_panel/special_games/captain.lua
If there was a race of the referee choosing exactly 2 captains, and others volunteering to be captain, then more than two players could end up on the captains list.
This would cause these players to be listed as a "captain" in the captains list even though they were not the captain of the team.
I also removed a similar race with someone adding themselves to the list of players just as the game started. This could theoretically have made it so that the player couldn't have been the first pick, but they would show up in the next pick screen, which would be funny.
I tested that the code still seems to work. I didn't actually reproduce the race condition manually or anything though.
=> Fix too-many-captains race condition

comfy_panel/poll.lua
I often want to make 30 second polls, which was near impossible before in the UI.  It is now more straightforward.
=> Poll duration: make it easier to make short-duration polls

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/ai_strikes.lua, maps/biter_battles_v2/feeding_calculations.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua
Without this change, we can end up with log entries like the following:
.../temp/currently-playing/utils/event_core.lua:30: Error caught: Given entity doesn't exist anymore.
.../temp/currently-playing/utils/event_core.lua:32: stack traceback:
.../temp/currently-playing/utils/event_core.lua:32: in function <...ctorio1.1.42/temp/currently-playing/utils/event_core.lua:29>
[C]: in function 'set_multi_command'
.../temp/currently-playing/maps/biter_battles_v2/ai.lua:51: in function '?'
.../temp/currently-playing/maps/biter_battles_v2/main.lua:408: in function <...42/temp/currently-playing/maps/biter_battles_v2/main.lua:388>
[C]: in function 'xpcall'
.../temp/currently-playing/utils/event_core.lua:49: in function 'call_handlers'
.../temp/currently-playing/utils/event_core.lua:61: in function …
=> Clean up errors in log

maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
Before this fix, if you got a message just before a map reset, then it would stay around permanently.
=> ping messages: fix permanent-ping from message before map reset

maps/biter_battles_v2/gui.lua
Adds `on_player_joined_team`  event.
This event is raised only once when a player joins a team for the first time.
Very useful for special games where need to give player items on join team. Current known solution is a wonky combination of  `on_player_changed_force` and a one-time `removable_nth_tick_function`. 
With `on_player_joined_team`  its possible to do it like this:
```
/c
local Gui = require "maps.biter_battles_v2.gui"
local Event = require 'utils.event'
Event.add_removable_function(Gui.events.on_player_joined_team, '
function(event)
local player = game.get_player(event.player_index)
player.insert{name = "rocket-silo", count = 1}
end
', "on_player_joined_team")
```
=> Add `on_player_joined_team` event

maps/biter_battles_v2/main.lua
Fix a bug where the wrong player was getting pinged.
To repeat the bug, 3 players run commands in the following sequence:
plater2: `/w player1`
player1: `/r`
plater3: `/w player1`
plater2: `/r` --- no ping happens for player1, only message
player1: `/r` --- ping for player3 and chat message for player2
Basically when you /whisper and then /reply to /reply, you not receive ping
=> Fix reply ping

comfy_panel/special_games/captain.lua, maps/biter_battles_v2/gui.lua, utils/ui/closable_frame.lua
Make the "Join Info" window harder to miss in captains games.
Fix a bug in captains games where the pick-player UI could be stuck open forever after a captains event finished.
Change "playerlist" in the top-left to no longer be a table, which should handle very long player names a bit better. It is also now sorted in alphabetical order.
Captains games: add a textbox where players can give info to captains to see during the picking phase
=> Random UI changes

comfy_panel/special_games/captain.lua
Implement min playtime of 30 minutes to join a captain game
The vote is not over yet though.
To test, just start a captain game and do that : /c global.total_time_online_players["yourPlayerNickName"] = 139081398193
(or whatever time you wanna test... you can see time in fish windows too, in case of doubt of ticks to minutes conversion)
https://discord.com/channels/823696400797138974/823771211421974579/1251979562754113648
(in progress)
=> Implement min playtime of 30 min to join captain game

maps/biter_battles_v2/difficulty_vote.lua, maps/biter_battles_v2/gui.lua
Specifically, before this change, the buttons would be destroyed + recreated every few seconds. If this destroy+recreate happened between the click of a button, and the actual tick that the click is recognized by the server, then the button click would have been lost before, and now it will not be. Thus, for users with high latency connections, it was very unreliable to click "join team" or "send science" buttons. After this change, the buttons should no longer be unreliable.
Note that this means that we potentially need to deal with double-clicks of buttons like the join button. Before, this was impossible, as the button was destroyed when it was clicked, and so the game engine would ignore any subsequent clicks. Now, we only hide the button (rather than destroy it), and so the game will …
=> Main gui: make buttons much more responsive

comfy_panel/special_games/captain.lua
Very small details but it would be nice to see the amount of players there are in the list to play, example :
=> Captain event : show amount of players before the players list

maps/biter_battles_v2/ai.lua
This means that if /difficulty-revote is run after one team has already fed, it will not reset evo of both teams (effectively undoing the feed).
=> /difficulty-revote no longer resets evo after teams have fed

comfy_panel/config.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
implementing game-vote.
https://discord.com/channels/823696400797138974/823771211421974579/1248907791087960068
how it is done.
on join or rejoin team function checks if u haven't got burners then check if in enemy team is connected player that also didn't get burners. if yes then insert 10 burners to both of you
=> implement burners balance.

comfy_panel/special_games/captain.lua
Change initial picking to be 1-2-2-2-2... always
Note that the picking system is more accurately described as "captains can continue to pick players until their team has more players than the other team". So if there is one group of 3 that is picked first, then the picking would go 3-4-2-2-2-...
Note that after the initial picking phase, it is always just captains-alternate-picking.
Replace late-pick-logic according to #game-vote. Specifically, this now prefers to give first-pick to the team with fewer players by 10% per player.
=> Captain pick order rework

comfy_panel/special_games/captain.lua, maps/biter_battles_v2/gui.lua
If a player is picked when they are offline, this should now make it so that they are still a spectator, but they can "rejoin team" after they reconnect.
=> captains: fix picking of offline players

comfy_panel/special_games/infinity_chest.lua, commands.lua, commands/inventory_costs.lua, maps/biter_battles_v2/feed_values_tab.lua, maps/biter_battles_v2/item_costs.lua
This should help identify people who are hoarding resources early in the game.
This also changes the infinity_chest special game to exclude items from /inventory-costs.
Note that this will only work when the infinity chests are created via this special-game codepath. Lots of snippets that admins use to create infinity chests will not do this, and thus the items will still be counted in /inventory-costs.
There is a large code refactor that is actually very simple (moving data from one file to another). It might be easiest to review this change one-commit-at-a-time, rather than all together.
=> add /inventory-costs comand

comfy_panel/special_games/captain.lua
There are two fixes here. One is straightforward, where it was odd that if you volunteered to be captain, but then said "actually, I don't want to play", you would remain as a captain volunteer.
The other is that I think that on a high latency connection, it would have been possible to do weird things (like volunteer to be captain *after* you had stated that you don't want to play) to end up in the same state.
Specifically, because we only change the visibility of these buttons, without actually destroying/recreating them, it is possible for network latency to cause clicks to appear even when the button would otherwise be disabled. Perhaps these could be fixed by checking for element.enabled in all cases, but I'm not sure.
Anyhow, I think that this should fix the issue that sticklord …
=> captains: fix some weird conditions with "I do not want to play/captain"

comfy_panel/special_games/captain.lua
- Join info panel layout changes:
- Added dividers to help split up the wall of text
- Grouped the 4 main join / unjoin buttons into 2 rows
- Updated the join button text to hopefully make it clearer so people don't just blindly click on both
- In the admin config panel, if the referee name is left blank, it now defaults to whoever activated the game
after:
before:
=> feat(ui/captains): minor join info panel layout update

comfy_panel/special_games/captain.lua, maps/biter_battles_v2/gui.lua, utils/player.lua
- extracted function from the main player list gui
- sort + colorize player names in captain game info panels
=> feat(captains): order and colorize player names in info panels

commands/inventory_costs.lua, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/tables.lua, maps/biter_battles_v2/team_stats_collect.lua, maps/biter_battles_v2/team_stats_compare.lua, utils/utils.lua
Here is a screenshot of (a slightly out-of-date version of the code) the screen from a game earlier today
This displays many stats that are useful to understand how the game went. By default, it is displayed for all users at game end. You can also see stats for the previous game with `/teamstats prev`
This change was enabled by proxc, who built awesome mock-ups of what the information should look like.
This should have almost no performance overhead, as we are just looking at production statistics once per 16 seconds, and running a little bit of extra code in the on_entity_died handler.
This also has better crash-protection code that can be used for commands (like `/teamstats`) to make them not crash the server on error.
=> End game stats UI

comfy_panel/special_games/captain.lua, commands/difficulty_voting_commands.lua, maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/difficulty_vote.lua, maps/biter_battles_v2/tables.lua, maps/biter_battles_v2/team_stats_collect.lua, maps/biter_battles_v2/team_stats_compare.lua
This gives a simpler option for admins to force the difficulty. Before this, it was necessary to first go Fish -> Config -> Admin-only-difficulty-voting-on, then run /difficulty-revote, then vote, then run /difficulty-close-vote.  Now you can just run one command.
This also fixes the difficulty-name/value listed in '/teamstats prev' which was previously broken, and improves some formating of long-team names in the /teamstats view.
=> /close-difficulty-vote: add optional param to force difficulty

comfy_panel/special_games/captain.lua
Eagle reported that terrible things happened when he momentarily was disconnected, and looking at this more closely, it seems like it was super broken. Especially if a captain ever left the game.... could end up swapping captain of south to be captain of north and other terrible things...
=> captains on_player_left_game: fix bugs hopefully

maps/biter_battles_v2/gui.lua
Player will spill all his burners on surface on_player_left_game
=> burners-balance. now player drop burners when left game

comfy_panel/main.lua, comfy_panel/poll.lua, commands/difficulty_voting_commands.lua, maps/biter_battles_v2/difficulty_vote.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/main.lua
This both makes it clearer in game, and gives the website an update about what happened.
Presumably the "Custom (222%)" difficulty messages will break the website slightly in some ways, but I don't really see a good way around that.
=> /close-difficulty-vote: add logging if difficulty changes

utils/event.lua
- A solve to desyncs due to removable functions and removable nth tick functions
- A new way to remove removable functions that is more convenient and safer to coding mistake
First of all, the desyncs were due to the function that loads the registered functions when the game is loaded (add_handlers, event.lua:556). It used a normal for loop to go through the table that contains the functions instead of an in pairs for loop. This caused an error when the first elements of that table are nil, but the error was not actually raised because of xpcall, which caused the registering of events stop, which caused a desync.
This problem happened when multiple functions with the same name are not removed at the same time, this happened with the special "scavenger" where the name of a function and the …
=> Special game desync fixes and change in removable functions

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/team_stats_collect.lua, maps/biter_battles_v2/team_stats_compare.lua
Follow up PR for https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/559
Add inventory tracking upon entity death to track lost items.
Entities are whitelisted to check their inventory upon death (whitelisted so we do even less unnecessary checks on frequent deaths such as walls, belts, poles which have no inventories). Works with chests, vehicles, machines, power structures...
=> Add inventory tracking for lost item teamstats

maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua, utils/queue.lua
I believe there is a slight performance improvement on init since whole map is not requested to be charted on that event, but the workload is spread over multiple ticks. On the other hand, there is the small overhead of running that function in background, but I think it only does the very minimal work needed (see `..init.lua` `Public.pop_chunk_request()`)
=> Fix ping alert and map countdown sound bugs

comfy_panel/special_games/captain_utils.lua, utils/player.lua
carl raised this issue to me
the player list was being sorted by player play time (on insert to player list)
in an earlier PR I updated the player list to be sorted by name (on render)
this PR reverts the sorting change
=> feat(captains): revert captains join info panel player list sort logic

comfy_panel/special_games/captain_task_group.lua
Error message in log during a captain game : 
**currently-playing/utils/event_core.lua:30: Error caught: ...playing/comfy_panel/special_games/captain_task_group.lua:157: attempt to index local 'groupsOrganization' (a nil value)**
Add condition to prevent showing task group for spectator. There is only groupsOrganization for north or south, but in some case, player will be able to get task group UI as spectator (player leave as spectator and come back spectator, will get the task group ui, and it will generate these errors)
=> Bugfix captain : dont show task group for spectators

maps/biter_battles_v2/difficulty_vote.lua
Fix problem where players in captains game could vote same difficulty multiple times.
=> Fix, prevent voting same difficulty: Now also in captains.

maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/main.lua
Follow up PR from https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/568
> It is now possible for admins to switch ON/OFF map reveal at ANY time, and not just before a new map. Which means, admins can interrupt/carry on map reveal at any time during the evolution of the map.
> "Big starting square" of 500 tiles each side will be requested once again at the end of map reveal (again, if map reveal switch is ON) to clear any visual bugs in hiccups/inconsistency of initial map reveal (see attachment)
=> Charting fixes

utils/player.lua
there was a bug where the unsorted list was used instead of the sorted player list
=> fix: teams player list no longer sorted

maps/biter_battles_v2/game_over.lua
Reduce the majority required for a map reroll from the current 75% to 66%
Vote : https://discord.com/channels/823696400797138974/823771211421974579/1264704865263943691
=> Reduce the majority required for a map reroll from 75% to 66%

maps/biter_battles_v2/init.lua, maps/biter_battles_v2/team_stats_collect.lua, maps/biter_battles_v2/team_stats_compare.lua
Specifically, this does the following things:
1. Adds a "Show more items" checkbox that displays rocket-components, rgb chips, redbelt, boilers+steam engines.
2. Adds science space-sci-equiv tooltips in a bunch of places
3. Adds a "buffered" column when "show more items" is checked that indicates how many of these items are buffered (i.e. items just sitting around).
4. Adds tooltips for each item-produced that include the "buffered" number.
5. Adds electric miners to the view all the time.
6. Some small display tweaks
7. When using `/c global.team_stats_use_fake_data = true`, the displayed numbers are chosen using `math.exp` so they should have a much more widely varying number of digits, much like real numbers in the game do, to make the display look a bit more realistic.
8. Puts in code …
=> teamstats: add a bit more info

commands/difficulty_voting_commands.lua, maps/biter_battles_v2/difficulty_vote.lua, maps/biter_battles_v2/feeding.lua
now voting time will use gui time instead of game.ticks_played
previously voting was closing even if no-one joined team.  
now players have 10 min to vote from the actual match start which is started by multiple actions like crafting mining.
=> Synchronize voting time with displayed time in gui. 

maps/biter_battles_v2/gui.lua
blocks possibility to join team if reroll voting is active
display message for a player when click join.
=> now can't join team if reroll didn't end.

maps/biter_battles_v2/game_over.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/team_stats_collect.lua
This should allow them to be part of captains game histories, and if someone builds a more generic database copying logic, they could also be taken from the logs in general for all games.
From my random sampling of the artifically/randomly generated numbers, it ends up as approximately 5kb worth of JSON data.
=> teamstats: log json version of stats in various places

maps/biter_battles_v2/main.lua
Possible fix to https://discord.com/channels/823696400797138974/1003021908796784800/1271577169344204821
For private messages, players can write the username in a different case, for example `/w PaveV` or `/w pavev`
Such messages will reach the user correctly. But this will create entries with different keys in the `global.reply_target table`
So then, in response with `/r` command, the wrong entry is chosen and the wrong player receives the notification.
=> Fix reply notification to wrong player

comfy_panel/poll.lua, maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/feeding_calculations.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/init.lua, maps/biter_battles_v2/team_stats_collect.lua
This just makes more sense to me. Examples of old-vs-new text:
```
"Revive: 0%"  -> "Health: 100%"
"Revive: 10%" -> "Health: 111%"
"Revive: 80%" -> "Health: 500%"
"Revive: 90%" -> "Health: 1000%"
```
This change should not actually impact gameplay at all, just what is displayed.
=> Replace "reanim_chance" with "biter_health_factor"

maps/biter_battles_v2/team_stats_compare.lua
This number was wrong, depending on mutagen effectiveness.
=> teamstats: fix space-sci-equiv-produced number

maps/biter_battles_v2/main.lua
Otherwise, it is odd to get warnings about being afk when captains games are in the planning phase but before they have started.
=> afk_kick: only kick once game starts

comfy_panel/special_games/captain.lua, comfy_panel/special_games/captain_utils.lua, locale/en/locale.cfg, utils/gui.lua
Captains games now support having a team be "captainless" (the actual captain variable is nil). In this case, all players are trusted to send science. When latejoiners need to be picked, they will be picked by a random player on the team chosen among the top 30% of players sorted by pick-order who are currently online.  In all captains games (whether they are community picked or not), this can be arranged with commands like `/replaceCaptainNorth !nobody!`.
Now, after a 'community-pick' game assigns people to teams, for each team, the players in the top 30% of the "pick order" are prompted to ask if they want to be a captain. They can answer one of Yes/Maybe/No (if they don't answer, it is the same as answering "no").  After 30 seconds, if people answered "Yes", then one of them is chosen …
=> Community pick captain improvements

locale/en/locale.cfg
Not much to say, this commit add back the text from automatic captain that got removed by a recent commit resulting in broken UI :  [PR604](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/604)
Added it back
=> Add back missing text for automatic captain poll that got removed 

comfy_panel/special_games/captain.lua
This adds an option for the referee to decide if there should be a captain volunteer-phase after teams are picked or not.
=> community pick: default to no captains, allow ref to decide

comfy_panel/special_games/captain.lua, comfy_panel/special_games/captain_community_pick.lua
Ignore self-placement because otherwise there is a slight incentive to place yourself last, which only some players will do, leading to less fair teams.
Don't allow spectators to submit rankings. In a random sample of games, a surprisingly high number of spectators rank players inaccurately/randomly with the belief that it doesn't matter.
=> captain community pick: ignore where people place themselves in the list

comfy_panel/special_games/captain.lua, comfy_panel/special_games/captain_community_pick.lua, maps/biter_battles_v2/game_over.lua
captain_mode: fix bug with game-stats-logging when a team is captainless to start out with
Add logging of community picks on the server
captain community pick: do not clear out special.communityPicksConfirmed after game start
Useful for debugging how/why things were picked as they were.
=> Community pick fixes/logging

comfy_panel/special_games.lua, comfy_panel/special_games/threat_farm_threshold.lua, maps/biter_battles_v2/ai.lua
Adds a threat threshold. Kills that would decrease threat further, increase enemy threat instead. 
The threshold and the fraction of excess threat, that gets added to the enemy can be configured.
Can be used to limit threat farming, or make it op for a fun game.
=> added threat farm special

maps/biter_battles_v2/shortcuts.lua
Fixed that it was possible to send science through a new UI shortcut button when sending science was disabled by a special game
=> Fix send science when disabled

maps/biter_battles_v2/shortcuts.lua
Fix that it was possible to send science and fish through the new UI hotkey after the game is over
=> Fix send science after game over

comfy_panel/special_games/captain.lua, maps/biter_battles_v2/init.lua
---Fill in---
This turned out to be quite easy.
The captain rendering is all being stored in global.special_games_variables.rendering, with keys of a name string (textId) and values of uint64 rendering IDs returned by rendering.draw_text() and analogous methods. As such, no new book keeping is required, just looping over these objects and destroying them specifically.
The one caveat is that the current implementation would destroy all special game rendering that is correctly registered within global.special_games_variables.rendering. I'm unsure if anyone actually uses it (I do not use it and barely knew the structures existed).
To make it compatible with this case, one can add `if string.sub(textId, 1, 7) == 'captain' then` into the new clear_captain_rendering() method to only remove …
=> Fix captain text render

comfy_panel/config.lua, comfy_panel/score.lua, maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/functions.lua
Biter nests health increases with evo (see [FFF-427](https://factorio.com/blog/post/fff-427)). This adjusts the score obtained by killing spawners according to the new approximated function of:
`y = 350 + 3150 * (x^2.25)`
resulting in
`factor = 1 + 9 * (evolution^2.25)`
which describes the factor of `nest_health / base_prototype_health` in function of evo(x). Note that this only applies up to 100% evo, after that, the threat reduction for killing (and health value of) the biter nests does not change.
=> Adjust nests value by evolution

maps/biter_battles_v2/gui.lua
If player is in remote view and joins a team for a first time then main inventory is nil. Let's fix that
=> Fix joining when in remote view

maps/biter_battles_v2/init.lua
This commit has unintended consequence, because it's also suppressing information who is queuing/cancelling tech in your own force. This will need to be done properly to avoid the issue.
=> Revert of tech notifications

maps/biter_battles_v2/init.lua
Because bbX surface was hidden from surface list player could see an alert, but it wasn't possible to click on it to zoom at location where it was triggered. The alert panel appeared broken. I found that hiding nauvis surface instead of bb surface makes the surface list go away, but now alerts works as they should.
=> Fix alert display

antigrief.lua, comfy_panel/special_games/disabled_entities.lua, commands/inventory_costs.lua, commands/suspend.lua, maps/biter_battles_v2/feeding.lua, maps/biter_battles_v2/feeding_calculations.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/team_manager.lua, modules/show_inventory.lua, utils/freeplay.lua
So far I was convinced that get_inventory is broken, but turns out you can easily use player.character.get_inventory to access it regardless of player's controller state. This information wasn't in 2.0 change log. This PR fixes all uses of get_inventory. I also managed to patch old bug that causes errors if /inventory is open for a player that has left already.
=> Fix uses of inventories

antigrief.lua, commands/inventory_costs.lua, maps/biter_battles_v2/feed_values_tab.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/item_costs.lua, maps/biter_battles_v2/team_stats_collect.lua, modules/show_inventory.lua
More fixes of some places affected by removal of RCU. Fixes some usages of changed API of `LuaInventory::get_contents`.
This allows to enable `/inventory-costs` command and 'FeedValues' tab from 'Menu & Settings'.
I also missed grayed out armor grid icons of `/inventory` ui, so this pull requests contains this fix as a continuation to https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/645
As a side note: to keep in mind, I've noticed that Factorio 2.0.22 has a breaking change (`LuaEquipmentGrid::get_contents` [old](https://lua-api.factorio.com/2.0.21/classes/LuaEquipmentGrid.html#get_contents) -> [new](https://lua-api.factorio.com/2.0.22/classes/LuaEquipmentGrid.html#get_contents)), which will affect, for example, this code …
=> Migration to Factorio 2.0 fixes

antigrief.lua, comfy_panel/admin.lua, comfy_panel/player_list.lua, commands/suspend.lua, commands/where.lua, maps/biter_battles_v2/gui.lua, maps/biter_battles_v2/main.lua, modules/corpse_markers.lua, modules/floaty_chat.lua, utils/alert.lua, utils/datastore/jail_data.lua, utils/game.lua
Next fields from `LuaPlayer` have changed their semantic and were renamed/moved:
* position -> physical_position
* surface -> physical_surface
* driving -> character.driving
* vehicle -> physical_vehicle
* controller_type -> physical_controller_type
Old names are still available, but they additionally reference remote view if it's active. This creates bizarre bugs and corner cases in the old code.
Here's non-exhaustive list of fixed issues:
* Admin teleporting of driving player while he's in remote view fails
* Admin teleporting of dead player error (in log)
* Admin "bring player/bring to spawn/go to player": incorrect destination position/surface while in remote view
* Admin "spank/damage": incorrect particle position while target in remote view
* Show player in player list: remote view …
=> Fixes related to subtle changes in Factorio 2.0 API

maps/biter_battles_v2/terrain.lua
After update to 2.0 `lab-white`  tile render level changed and now it renders over other tiles. This PR fixes it with white sprites.
=> Fix New Year Island snow transition

maps/biter_battles_v2/functions.lua
Co-author: floortiler
Technologies from the group 'energy-weapons-damage' were silently renamed to 'laser-weapons-damage' during some of Factorio update.
Laser turret values before change:
20
20 + 4
20 + 8
20 + 14
20 + 22
20 + 32
20 + 46
20 + 60
20 + 74
After:
20
20 + 8.8
20 + 13.6
20 + 27.6
20 + 38.8
20 + 52.8
20 + 79
20 + 100
20 + 121
=> Fixed laser damage buff wasn't applied due to technology rename

maps/biter_battles_v2/functions.lua
Some changes to map reset:
- Latest test revealed corner case with construction bots being teleported along with player to new surface. The only way to get rid of them is to get rid of character. Too bad it wasn't documented in the code originally.
- The second issue is that calling LuaControl::clear_items_inside() did not clear all items inside a character contrary to what is specified in documentation. Items were deleted only partially.
- From now on we're going to be extra sure that some teleport point is always returned even if find_non_colliding_position has failed.
- This change sandbags character creation to the point it should be _impossible_ for it to fail with double surface or cause non recoverable exception. If some player still losses character randomly, it's reported into …
=> Another attempt at fixing player missing character during map reset

maps/biter_battles_v2/team_manager.lua
Sometimes when player was picked in captain game their character was missing, but no fail was produced. The issue occurred when player was looking at not generated chunk and was picked/switched at the same time. Especially problematic during captain event.
Trigger mechanism found by @developer-8
=> Fix missing character bug when switching teams

maps/biter_battles_v2/mirror_terrain.lua, maps/biter_battles_v2/terrain.lua
- Fix south team having water under base due to use of .valid property in hidden tile mirroring which always was nil.
- Optimize spawn area generation on top of lakes by removing tile replacement search and using constant value.
=> Optimize and fix bug in hidden tile mirroring

comfy_panel/special_games/captain.lua
Currently during captain special it's easy to predict on which forces captains end up:
* If captains accepted by a referee, the earliest willing captain (first in the captain volunteer list) will end up on north.
* If it's auto captain special, the player from captain volunteer list with the most play time will end up on north.
This change makes so it's objectively unpredictive on which sides captains end up.
=> Change so captains during the special join random forces

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/main.lua
New player character was created every time a player rejoined. They would even get ejected from a team upon rejoin. It happened because part of on_player_joined logic was centralized in common function without proper exit condition and so entire function was executed.
=> Partial revert of fix introduced in #670

utils/event_core.lua
Each Factorio session was launched on its own through CL option `./factorio --enable-unsafe-lua-debug-api`, and performing a similar amount of updates at `game.speed = 1` on a AMD Ryzen 7800x3D.
Comparison between #677, #678, and #681 using the in-game `/startProfiler`.
```
Deep Copy (master)
3602x "anonymous" in "event_core.lua", line 56. Total Elapsed: 417.046229ms
3602x "call_handlers" in "event_core.lua", line 36. Total Elapsed: 401.815727ms
Shallow Copy (PR #677)
3602x "anonymous" in "event_core.lua", line 56. Total Elapsed: 198.237986ms
3602x "call_handlers" in "event_core.lua", line 36. Total Elapsed: 182.213295ms
Linked List (PR #678)
3602x "anonymous" in "event_core.lua", line 48. Total Elapsed: 241.542714ms
3602x "call_handlers" in "event_core.lua", line 38. Total Elapsed: …
```
=> Loop handlers backwards

maps/biter_battles_v2/gui.lua
Costly operations, that are common for all players, have been moved to separate function.
Now clock, evolution, threat, playerlists etc. are constructed once every refresh instead of once for every player.
Testing performance improvements should be done on live server, as the gain is expected to be proportional to number of players
=> Fix inefficient gui refresh

maps/biter_battles_v2/feeding.lua
Fix https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/689
Issue: before game starts, player is allowed to send all science but not single foods.
Correct behavior is that players shouldnt be allowed to send any packs (single/all) before game starts (which happens when 1st entity is mined or when CPT game says so).
SO the Feeding.sends_mixed should not allow time == (because 0 == 0 is always true)
=> Fix send all permissions on game start #689

comfy_panel/special_games/captain.lua, maps/biter_battles_v2/main.lua
As per poll on discord: [Make NORTH and SOUTH chat not visible to spectators in CPT games during picking phase to keep plans secret during preparation phase until game has started](https://discord.com/channels/823696400797138974/823705092372430869/1330209572757049577): 21 in favor vs 0 against. 
Does not forward NTH ans STH chats to spectator force during preparation phase of cpt games. Lifts the curtains once the game starts.
Added game.prints to inform all players (nth, sth, spect) of when the chat is hidden/revealed
=> Conceal CPT team chats during planning

maps/biter_battles_v2/biter_raffle.lua, tests/test-biter_raffle.lua
2 more steps of optimizing `biter_raffle`:
1) Switch `raffle` table into array - 104ms => 84ms - ~20% improvement
2) Reuse one "global" `raffle` table instead recreating it on each call - 84ms => 64ms - another ~20% improvement
Unfortunately, switching to arrays broke the tests, so they had to be updated as well.
It probably can be optimized a bit more, by skipping unnecessary `return` statements, but for sake of comparability (and in order not to break any more tests), I've left it as is for now
Based on ideas form @vadcx  in #477
=> Biter raffle take 2

commands/chat_commands.lua, maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/main.lua
1) Tightened the loop by iterating only on connected players
2) Removed `colorChosen == nil` check, as `print(msg, {color = nil})` works just fine
=> print_message_to_players() tweaks

utils/profiler.lua
Replaced all `print` statements, that have to be identical for all clients, with `log` that seems not to be synchronized.
Profiler can be enabled by player that started Factorio with `--enable-unsafe-lua-debug-api ` flag. This option can be enabled by players individually and does not cause desyncs itself.
Orginal idea by @DaTa- 
> This is about the old profiler: turns out printing in console in synchronized so any prints which are done behind `isProfilingSupported()` will desync all clients who disagree on `--enable-unsafe-lua-debug-api` with the server.
It's worth mentioning that the performance of this code is still terrible, and dropouts related to falling behind the server might occur. #695 aims at introducing new profiler version with improved performance, although it comes at the …
=> Fix desyncs caused by profiler in Factorio 2.0

maps/biter_battles_v2/gui.lua
added player.clear_cursor() in Gui.clear_copy_history(player) function, before cursor stack is overwritten by new one.
is it ok?
=> fix: cursor stack no longer lost when disconnecting. 

comfy_panel/special_games/captain.lua, comfy_panel/special_games/captain_pick.lua, comfy_panel/special_games/captain_task_group.lua, comfy_panel/special_games/captain_utils.lua, locale/en/locale.cfg, utils/gui.lua, utils/string.lua
---
> Enrollment
Players volunteer to CPT games & CPT role with usual UI: when clicking "I want to play", in addition to the note field, a list of "Tasks" will also be visible: player can click upon any number of task to mark what they could contribute with (buttons have tooltips with the meaning of the task)
---
> This is how the new UI will look like at first:
- "Pin" button to Minimize/Maximize window
- "Settings" button (Referee only)
> Minimized version of the full window
Minimized version will only show the chess clock & tooltips of displayed info (see "Footer" section for more details)
> Referee's settings menu
Referee settings menu is self explanatory, referee can:
- add/remove +1/-1 picks to each team individually (current round, default settings 1-2-2-2...)
- force a team to be …
=> Add new Captain Pick UI

maps/biter_battles_v2/gui.lua
Don't use LuaPlayer::spectator property to judge whether player is in fact spectator or not. This property has nothing to do with force assignment and can be manipulated from player setting in comfy panel at will. This can lead to a situation where player without a character is moved to spectator island and spectator initialization code is not executed for them.
=> Ignore LuaPlayer::spectator in spectate()

maps/biter_battles_v2/init.lua
Enable ctrl-c for spectators so they can use it to count entities.
=> Enable ctrl-c for spectators

maps/biter_battles_v2/mirror_terrain.lua
1. Skipped `src_pos.x == dest_pos.x` check, as it is always true
2. Replaced `src_pos.y == dest_pos.y` with `dest_pos.y == 0`, as it can be true only in this case
3. Removed unused `src_pos`
4. Reordered so that `return` check is made as soon as possible
5. Replaced `local source = event.source` declaration used only once in `local dest_pos = source.position`, with direct `local dest_pos = event.source.position`
3600 tick profile right after map restart:
```
before:
117502x "invert_entity". Total Duration: 19746.395700ms avg: 0.16805157ms
1527712x "__index". Total Duration: 7555.191300ms
117502x "teleport". Total Duration: 912.231100ms
582x "__newindex". Total Duration: 9.324700ms
106x "table_insert". Total Duration: 0.573600ms
after:
129379x "invert_entity". Total Duration: …
```
=> Optimized destination position calculation in invert_entity()

comfy_panel/special_games/captain.lua, comfy_panel/special_games/captain_pick.lua, maps/biter_battles_v2/init.lua
Command:
1. needs to be run by any admin any time **before** the start of the cpt picking phase (not after the captains are already able to pick, else it needs a reset of cpt mode)
2. default will use new UI
However, I plan to remove this command and setting in storage after new UI is considered stable. This is just a handy fallback to old mode without the need to reload scenario and everything else.
If new UI breaks, Ref can Disable it from settings, run the toggle command, and proceed with old UI simply, without losing current seeded map.
=> Add admin fallbacks for new pick UI

commands/announce.lua
- Adding support for new line character in the /announce command.
- Adding /announce-append command which appends to the existing announcement if any, or create a new one otherwise.
=> Add \n and appending support to announces

maps/biter_battles_v2/feeding.lua
`{str1  .. str2 .. str3}` equals `{str1str2str3}` (single entry array).
It has to be either `str1  .. str2 .. str3` or `table.concat{str1 , str2 , str3}`
This is a waste of time:
```
t = { 0 }
for _ = 1, 7 do
table.insert(t, 0)
end
```
The size of this array is fixed and known beforehand:
```
t={ 0,0,0,0,0,0,0,0 }
```
=> Fixed incorret usages of table.concat

maps/biter_battles_v2/ai.lua, maps/biter_battles_v2/tables.lua, tests/test-feeding.lua
Adjusting mutagen values according to poll https://discord.com/channels/823696400797138974/823771211421974579/1389238457678692445
The vote passed with 82% of the community agreeing (9 for, 2 against)
-     Blue mutagen 265 -> 292
-     Yellow sci mutagen 2100 -> 2205
-     Remove delaying the difficulty ramping by 30 minutes
-     test feeding fixed for new values
=> Adjusting mutagen values according to poll

maps/biter_battles_v2/functions.lua, maps/biter_battles_v2/gui.lua
As stated in the subject. This gets rid of annoying situation where random players join server for the first time and have dark/black colors in chat which is difficult to read.
=> Initialize colors of players joining the server for the first time
